//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Account {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Account() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Experts.Resources.App_LocalResources.Account", typeof(Account).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O mnie.
        /// </summary>
        public static string AboutMe {
            get {
                return ResourceManager.GetString("AboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twoje konto Asknuts zostało utworzone poprawnie. Na podany adres e-mail został wysłany link aktywacyjny. Aby rozpocząć korzystanie z serwisu, aktywuj swoje konto przy pomocy otrzymanego linka..
        /// </summary>
        public static string AccountCreated {
            get {
                return ResourceManager.GetString("AccountCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twoje konto Asknuts zostało utworzone poprawnie. Na podany adres e-mail został wysłany link aktywacyjny. Przed ponownym zalogowaniem do serwisu w przyszłości, aktywuj swoje konto przy pomocy otrzymanego linka..
        /// </summary>
        public static string AccountCreatedFromPayment {
            get {
                return ResourceManager.GetString("AccountCreatedFromPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konto nie zostało aktywowane..
        /// </summary>
        public static string AccountNotActivated {
            get {
                return ResourceManager.GetString("AccountNotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link aktywacyjny został ponownie wysłany na podany adres..
        /// </summary>
        public static string ActivationEmailResent {
            get {
                return ResourceManager.GetString("ActivationEmailResent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyślij ponownie e-mail aktywacyjny.
        /// </summary>
        public static string ActivationResend {
            get {
                return ResourceManager.GetString("ActivationResend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twoje konto zostało aktywowane. Zaloguj się, aby korzystać z serwisu..
        /// </summary>
        public static string ActivationSuccessful {
            get {
                return ResourceManager.GetString("ActivationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miasto....
        /// </summary>
        public static string AddressCityEnterText {
            get {
                return ResourceManager.GetString("AddressCityEnterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konto zostało już wcześniej aktywowane..
        /// </summary>
        public static string AlreadyActivated {
            get {
                return ResourceManager.GetString("AlreadyActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zostałeś już zarejestrowany jako ekspert..
        /// </summary>
        public static string AlreadyExpert {
            get {
                return ResourceManager.GetString("AlreadyExpert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeżeli posiadasz już konto użytkownika w serwisie Asknuts.
        /// </summary>
        public static string AlreadyHaveUserAccount {
            get {
                return ResourceManager.GetString("AlreadyHaveUserAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zostałeś już zarejestrowany jako partner..
        /// </summary>
        public static string AlreadyPartner {
            get {
                return ResourceManager.GetString("AlreadyPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aby ułatwić korzystanie z serwisu, zostało dla Ciebie założone anonimowe konto użytkownika. Umożliwia ono przeglądanie historii pytań i odpowiedzi. Aby zalogować się do konta w przyszłości, skorzystaj z linka wysłanego na podany adres e-mail..
        /// </summary>
        public static string AnonymousAccountCreated {
            get {
                return ResourceManager.GetString("AnonymousAccountCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to anonimowy.
        /// </summary>
        public static string AnonymousUsername {
            get {
                return ResourceManager.GetString("AnonymousUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadaj mi swoje pytanie.
        /// </summary>
        public static string AskMeAQuestion {
            get {
                return ResourceManager.GetString("AskMeAQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawny e-mail lub hasło..
        /// </summary>
        public static string AuthenticationFailed {
            get {
                return ResourceManager.GetString("AuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To wizualna reprezentacja twojego użytkownika w serwisie. Serwis akceptuje pliki w formatach: jpg, bmp oraz png. Obraz nie może przekroczyć rozmiaru 2MB i po przesłaniu zostanie przeskalowany do rozmiaru 300 na 300 pikseli..
        /// </summary>
        public static string AvatarUploadInfo {
            get {
                return ResourceManager.GetString("AvatarUploadInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powrót do edycji profilu.
        /// </summary>
        public static string BackToProfile {
            get {
                return ResourceManager.GetString("BackToProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Środki dostępne.
        /// </summary>
        public static string BalanceAvailableValue {
            get {
                return ResourceManager.GetString("BalanceAvailableValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data zlecenia.
        /// </summary>
        public static string BalanceOrderDateColumn {
            get {
                return ResourceManager.GetString("BalanceOrderDateColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tytuł transakcji.
        /// </summary>
        public static string BalanceTitleColumn {
            get {
                return ResourceManager.GetString("BalanceTitleColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktulne saldo.
        /// </summary>
        public static string BalanceTotalValue {
            get {
                return ResourceManager.GetString("BalanceTotalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data realizacji.
        /// </summary>
        public static string BalanceTransferDateColumn {
            get {
                return ResourceManager.GetString("BalanceTransferDateColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartość.
        /// </summary>
        public static string BalanceValueColumn {
            get {
                return ResourceManager.GetString("BalanceValueColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer konta bankowego do wpłaty.
        /// </summary>
        public static string BankAccountNumber {
            get {
                return ResourceManager.GetString("BankAccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj numer konta bankowego na które mają zostać wpłacone pieniądze.
        /// </summary>
        public static string BankAccountNumberRequired {
            get {
                return ResourceManager.GetString("BankAccountNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zostań ekspertem.
        /// </summary>
        public static string BecomeExpert {
            get {
                return ResourceManager.GetString("BecomeExpert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorie zostały zaktualizowane..
        /// </summary>
        public static string CategoriesUpdated {
            get {
                return ResourceManager.GetString("CategoriesUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorie zostały zaktualizowane. Ponieważ wybrana została nowa kategoria, proces weryfikacji zostanie przeprowadzony ponownie..
        /// </summary>
        public static string CategoriesUpdatedForVerified {
            get {
                return ResourceManager.GetString("CategoriesUpdatedForVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj kategorię, w której specjalizuję się ekspert.
        /// </summary>
        public static string CategoryRequired {
            get {
                return ResourceManager.GetString("CategoryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pytania.
        /// </summary>
        public static string ChartAnswers {
            get {
                return ResourceManager.GetString("ChartAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oceny.
        /// </summary>
        public static string ChartFeedbacks {
            get {
                return ResourceManager.GetString("ChartFeedbacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przychód.
        /// </summary>
        public static string ChartIncome {
            get {
                return ResourceManager.GetString("ChartIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiadomość.
        /// </summary>
        public static string ChatMessageText {
            get {
                return ResourceManager.GetString("ChatMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wprowadź treść wiadomości.
        /// </summary>
        public static string ChatMessageTextRequired {
            get {
                return ResourceManager.GetString("ChatMessageTextRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musisz zaznaczyć to pole..
        /// </summary>
        public static string CheckBoxUnchecked {
            get {
                return ResourceManager.GetString("CheckBoxUnchecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz zdjęcie.
        /// </summary>
        public static string ChooseAvatar {
            get {
                return ResourceManager.GetString("ChooseAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skomentuj.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj komentarz .
        /// </summary>
        public static string CommentRequired {
            get {
                return ResourceManager.GetString("CommentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asknuts - kontakt.
        /// </summary>
        public static string ContactEmailFrom {
            get {
                return ResourceManager.GetString("ContactEmailFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba znaków w opisie nie może przekroczyć 230..
        /// </summary>
        public static string DescriptionTooLong {
            get {
                return ResourceManager.GetString("DescriptionTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie masz jeszcze konta użytkownika?.
        /// </summary>
        public static string DontHaveAccount {
            get {
                return ResourceManager.GetString("DontHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres e-mail został już użyty. Podaj inny adres..
        /// </summary>
        public static string DuplicateEmail {
            get {
                return ResourceManager.GetString("DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podana publiczna nazwa użytkownika jest już zajęta..
        /// </summary>
        public static string DuplicatePublicName {
            get {
                return ResourceManager.GetString("DuplicatePublicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edytuj kompetencje.
        /// </summary>
        public static string EditExpertCategoryAttributes {
            get {
                return ResourceManager.GetString("EditExpertCategoryAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj profil.
        /// </summary>
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres e-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link z potwierdzeniem został wysłany na podany adres. Twój adres e-mail zostanie zmieniony dopiero po kliknięciu linka znajdującego się w otrzymanej wiadomości..
        /// </summary>
        public static string EmailChanged {
            get {
                return ResourceManager.GetString("EmailChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres został zmieniony poprawnie..
        /// </summary>
        public static string EmailConfirmationSuccessful {
            get {
                return ResourceManager.GetString("EmailConfirmationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można znaleźć użytkownika. Upewnij się, że użyty link jest poprawny..
        /// </summary>
        public static string EmailConfirmationUserNotFound {
            get {
                return ResourceManager.GetString("EmailConfirmationUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawny adres e-mail.
        /// </summary>
        public static string EmailIncorrect {
            get {
                return ResourceManager.GetString("EmailIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpisz adres e-mail.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadowolonych klientów.
        /// </summary>
        public static string ExpertAcceptedAnswers {
            get {
                return ResourceManager.GetString("ExpertAcceptedAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atrybuty eksperta w kategorii {0} zostały zmienione.
        /// </summary>
        public static string ExpertCategoryAttributesChanged {
            get {
                return ResourceManager.GetString("ExpertCategoryAttributesChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprecyzuj swoje kompetencje w kategorii.
        /// </summary>
        public static string ExpertCategoryAttributesForCategory {
            get {
                return ResourceManager.GetString("ExpertCategoryAttributesForCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gratulujemy! Zostałeś Ekspertem..
        /// </summary>
        public static string ExpertConfirmation {
            get {
                return ResourceManager.GetString("ExpertConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zweryfikowany expert.
        /// </summary>
        public static string ExpertIsVerified {
            get {
                return ResourceManager.GetString("ExpertIsVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niezweryfikowany ekspert.
        /// </summary>
        public static string ExpertNotVerified {
            get {
                return ResourceManager.GetString("ExpertNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekspert nie został zweryfikowany przez serwis..
        /// </summary>
        public static string ExpertNotVerifiedInstructions {
            get {
                return ResourceManager.GetString("ExpertNotVerifiedInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozytywne opinie.
        /// </summary>
        public static string ExpertPositiveFeedback {
            get {
                return ResourceManager.GetString("ExpertPositiveFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil eksperta.
        /// </summary>
        public static string ExpertProfileTitle {
            get {
                return ResourceManager.GetString("ExpertProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opisz swoje doświadczenie w tej dziedzinie.
        /// </summary>
        public static string ExpertReasonPlaceholder {
            get {
                return ResourceManager.GetString("ExpertReasonPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twoje kompetencje.
        /// </summary>
        public static string ExpertReasonTitle {
            get {
                return ResourceManager.GetString("ExpertReasonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba znaków w opisie nie może przekroczyć 200..
        /// </summary>
        public static string ExpertReasonTooLong {
            get {
                return ResourceManager.GetString("ExpertReasonTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weryfikacja eksperta:.
        /// </summary>
        public static string ExpertVerification {
            get {
                return ResourceManager.GetString("ExpertVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oceny moich odpowiedzi.
        /// </summary>
        public static string FeedbacksToMyAnswers {
            get {
                return ResourceManager.GetString("FeedbacksToMyAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imię.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj imię.
        /// </summary>
        public static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przejdź do strony logowania.
        /// </summary>
        public static string GoToSignIn {
            get {
                return ResourceManager.GetString("GoToSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masz anonimowe konto?.
        /// </summary>
        public static string GotTemporaryAccount {
            get {
                return ResourceManager.GetString("GotTemporaryAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jestem ekspertem z dziedziny.
        /// </summary>
        public static string IAmExpertIn {
            get {
                return ResourceManager.GetString("IAmExpertIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwisko.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj nazwisko.
        /// </summary>
        public static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres e-mail.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpisz nazwę użytkownika lub adres e-mail.
        /// </summary>
        public static string LoginRequired {
            get {
                return ResourceManager.GetString("LoginRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfiguracja wiadomości pocztowych została zauktualizowana.
        /// </summary>
        public static string MailCfgUpdated {
            get {
                return ResourceManager.GetString("MailCfgUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt.
        /// </summary>
        public static string MailContact {
            get {
                return ResourceManager.GetString("MailContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Od odpowiadającego.
        /// </summary>
        public static string MailFromAnswerer {
            get {
                return ResourceManager.GetString("MailFromAnswerer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Od pytającego.
        /// </summary>
        public static string MailFromQuestioner {
            get {
                return ResourceManager.GetString("MailFromQuestioner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twój opis profilu.
        /// </summary>
        public static string MicroprofileDescription {
            get {
                return ResourceManager.GetString("MicroprofileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obecne stanowisko.
        /// </summary>
        public static string MicroprofilePosition {
            get {
                return ResourceManager.GetString("MicroprofilePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tytuł naukowy.
        /// </summary>
        public static string MicroprofileTitle {
            get {
                return ResourceManager.GetString("MicroprofileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil został zaktualizowany..
        /// </summary>
        public static string MicroprofileUpdated {
            get {
                return ResourceManager.GetString("MicroprofileUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil został zaktualizowany. Wkrótce zostanie on zweryfikowany przez naszego konsultanta..
        /// </summary>
        public static string MicroprofileUpdatedForVerified {
            get {
                return ResourceManager.GetString("MicroprofileUpdatedForVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to negatywnych.
        /// </summary>
        public static string Negative {
            get {
                return ResourceManager.GetString("Negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to neutralnych.
        /// </summary>
        public static string Neutral {
            get {
                return ResourceManager.GetString("Neutral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propozycja nowej kategorii.
        /// </summary>
        public static string NewCategory {
            get {
                return ResourceManager.GetString("NewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak Twojej specjalizacji?.
        /// </summary>
        public static string NewCategoryAttributeLabel {
            get {
                return ResourceManager.GetString("NewCategoryAttributeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaproponuj nową.
        /// </summary>
        public static string NewCategoryAttributeLink {
            get {
                return ResourceManager.GetString("NewCategoryAttributeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kontakt@asknuts.com.
        /// </summary>
        public static string NewCategoryAttributeMail {
            get {
                return ResourceManager.GetString("NewCategoryAttributeMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaproponuj specjalizację.
        /// </summary>
        public static string NewCategoryAttributeMailSubject {
            get {
                return ResourceManager.GetString("NewCategoryAttributeMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napisz do nas ze swoją propozycją!.
        /// </summary>
        public static string NewCategoryLink {
            get {
                return ResourceManager.GetString("NewCategoryLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kontakt@asknuts.com.
        /// </summary>
        public static string NewCategoryMail {
            get {
                return ResourceManager.GetString("NewCategoryMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak kategorii w której jesteś ekspertem?.
        /// </summary>
        public static string NewCategoryProposal {
            get {
                return ResourceManager.GetString("NewCategoryProposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pozytywnych opinii.
        /// </summary>
        public static string OfPositiveComments {
            get {
                return ResourceManager.GetString("OfPositiveComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stare hasło.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        public static string OpinionAddress {
            get {
                return ResourceManager.GetString("OpinionAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krótki opis.
        /// </summary>
        public static string OpinionContent {
            get {
                return ResourceManager.GetString("OpinionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opisz w paru zdaniach co sądzisz o serwisie Asknuts.
        /// </summary>
        public static string OpinionContentEnterText {
            get {
                return ResourceManager.GetString("OpinionContentEnterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data utworzenia.
        /// </summary>
        public static string OpinionCreationDate {
            get {
                return ResourceManager.GetString("OpinionCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocena serwisu.
        /// </summary>
        public static string OpinionMark {
            get {
                return ResourceManager.GetString("OpinionMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negatywnie.
        /// </summary>
        public static string OpinionMarkNegative {
            get {
                return ResourceManager.GetString("OpinionMarkNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozytywnie.
        /// </summary>
        public static string OpinionMarkPositive {
            get {
                return ResourceManager.GetString("OpinionMarkPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twoja opinia serwisu.
        /// </summary>
        public static string OpinionTitle {
            get {
                return ResourceManager.GetString("OpinionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zostałeś zgłoszony do uczestnictwa w programie partnerskim. Kiedy zgłoszenie zostanie zaakceptowane, poinformujemy Cię o tym poprzez wiadomość e-mail..
        /// </summary>
        public static string PartnerConfirmation {
            get {
                return ResourceManager.GetString("PartnerConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statystyki partnera.
        /// </summary>
        public static string PartnerStatistics {
            get {
                return ResourceManager.GetString("PartnerStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło zostało zmienione..
        /// </summary>
        public static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powtórz hasło.
        /// </summary>
        public static string PasswordConfirmation {
            get {
                return ResourceManager.GetString("PasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przypomnij mi hasło.
        /// </summary>
        public static string PasswordForgotten {
            get {
                return ResourceManager.GetString("PasswordForgotten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail z linkiem do resetu hasła został wysłany na podany adres..
        /// </summary>
        public static string PasswordForgottenInstructions {
            get {
                return ResourceManager.GetString("PasswordForgottenInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawne hasło.
        /// </summary>
        public static string PasswordIncorrect {
            get {
                return ResourceManager.GetString("PasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasła muszą się zgadzać.
        /// </summary>
        public static string PasswordMismatch {
            get {
                return ResourceManager.GetString("PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpisz hasło.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło zostało zresetowane pomyślnie. Zapisz podane niżej nowe hasło. Możesz je zmienić w panelu konfiguracyjnym konta..
        /// </summary>
        public static string PasswordResetInstructions {
            get {
                return ResourceManager.GetString("PasswordResetInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potwierdzenie zresetowania hasła..
        /// </summary>
        public static string PasswordResetTitle {
            get {
                return ResourceManager.GetString("PasswordResetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło musi mieć minimum {2} znaków.
        /// </summary>
        public static string PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wypłać środki.
        /// </summary>
        public static string PayoffOrder {
            get {
                return ResourceManager.GetString("PayoffOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartość nie może przekroczyć {0} zł.
        /// </summary>
        public static string PayoffValueToHigh {
            get {
                return ResourceManager.GetString("PayoffValueToHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartość analizowanych Pytań.
        /// </summary>
        public static string PendingQuestionsValue {
            get {
                return ResourceManager.GetString("PendingQuestionsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer telefonu.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer telefonu został zmieniony.
        /// </summary>
        public static string PhoneNumberChanged {
            get {
                return ResourceManager.GetString("PhoneNumberChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer telefonu został zmieniony. Wkrótce zostanie on zweryfikowany przez naszego konsultanta..
        /// </summary>
        public static string PhoneNumberChangedToVerify {
            get {
                return ResourceManager.GetString("PhoneNumberChangedToVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieprawidłowy numer telefonu.
        /// </summary>
        public static string PhoneNumberIncorrect {
            get {
                return ResourceManager.GetString("PhoneNumberIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj numer telefonu.
        /// </summary>
        public static string PhoneNumberRequired {
            get {
                return ResourceManager.GetString("PhoneNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zapoznałem się i akceptuję .
        /// </summary>
        public static string PolicyAcceptation {
            get {
                return ResourceManager.GetString("PolicyAcceptation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  oraz .
        /// </summary>
        public static string PolicyAcceptationAnd {
            get {
                return ResourceManager.GetString("PolicyAcceptationAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapoznałem się i akceptuję .
        /// </summary>
        public static string PolicyPrivateAcceptation {
            get {
                return ResourceManager.GetString("PolicyPrivateAcceptation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to politykę prywatności.
        /// </summary>
        public static string PolicyPrivateAcceptationClickHere {
            get {
                return ResourceManager.GetString("PolicyPrivateAcceptationClickHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polityka prywatności:.
        /// </summary>
        public static string PolicyPrivateTitle {
            get {
                return ResourceManager.GetString("PolicyPrivateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musisz zaakceptować politykę prywatności..
        /// </summary>
        public static string PolicyPrivateUnchecked {
            get {
                return ResourceManager.GetString("PolicyPrivateUnchecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musisz zaakceptować regulamin strony oraz politykę prywatności..
        /// </summary>
        public static string PolicyUnchecked {
            get {
                return ResourceManager.GetString("PolicyUnchecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapoznałem się i akceptuję .
        /// </summary>
        public static string PolicyWebAcceptation {
            get {
                return ResourceManager.GetString("PolicyWebAcceptation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to regulamin strony.
        /// </summary>
        public static string PolicyWebAcceptationClickHere {
            get {
                return ResourceManager.GetString("PolicyWebAcceptationClickHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regulamin strony:.
        /// </summary>
        public static string PolicyWebTitle {
            get {
                return ResourceManager.GetString("PolicyWebTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musisz zaakceptować regulamin strony..
        /// </summary>
        public static string PolicyWebUnchecked {
            get {
                return ResourceManager.GetString("PolicyWebUnchecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba znaków w tytule nie może przekroczyć 25..
        /// </summary>
        public static string PositionTooLong {
            get {
                return ResourceManager.GetString("PositionTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pozytywnych.
        /// </summary>
        public static string Positive {
            get {
                return ResourceManager.GetString("Positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zdjęcie użytkownika.
        /// </summary>
        public static string ProfileImage {
            get {
                return ResourceManager.GetString("ProfileImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zdjęcie użytkownika zostało zmienione.
        /// </summary>
        public static string ProfileImageChanged {
            get {
                return ResourceManager.GetString("ProfileImageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przenieś i upuść zdjęcie na wyznaczonym polu!.
        /// </summary>
        public static string ProfileImageInstructions {
            get {
                return ResourceManager.GetString("ProfileImageInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niewłaściwy format obrazu..
        /// </summary>
        public static string ProfileImageUploadError {
            get {
                return ResourceManager.GetString("ProfileImageUploadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publiczna nazwa użytkownika.
        /// </summary>
        public static string PublicName {
            get {
                return ResourceManager.GetString("PublicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publiczna nazwa użytkownika została zmieniona..
        /// </summary>
        public static string PublicNameChanged {
            get {
                return ResourceManager.GetString("PublicNameChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publiczna nazwa użytkownika została zmieniona. Wkrótce zostanie ona zweryfikowana przez naszego konsultanta..
        /// </summary>
        public static string PublicNameChangedForVerified {
            get {
                return ResourceManager.GetString("PublicNameChangedForVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz swoją publiczną nazwę użytkownika.
        /// </summary>
        public static string PublicNameRequired {
            get {
                return ResourceManager.GetString("PublicNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publiczna nazwa użytkownika musi mieć conajmniej 2 znaki i conajwyżej 25 znaków..
        /// </summary>
        public static string PublicNameTooLong {
            get {
                return ResourceManager.GetString("PublicNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zły format nazwy publicznej, sprawdź czy nazwa nie zawiera niewspieranych znaków..
        /// </summary>
        public static string PublicNameWrongFormat {
            get {
                return ResourceManager.GetString("PublicNameWrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loguj!.
        /// </summary>
        public static string QuickSignIn {
            get {
                return ResourceManager.GetString("QuickSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpisz poprawne dane,.
        /// </summary>
        public static string QuickSignInEnterCorrectData {
            get {
                return ResourceManager.GetString("QuickSignInEnterCorrectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to w serwisie..
        /// </summary>
        public static string QuickSignInInAskNuts {
            get {
                return ResourceManager.GetString("QuickSignInInAskNuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres e-mail.
        /// </summary>
        public static string QuickSignInLoginPlaceholder {
            get {
                return ResourceManager.GetString("QuickSignInLoginPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lub.
        /// </summary>
        public static string QuickSignInOr {
            get {
                return ResourceManager.GetString("QuickSignInOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło.
        /// </summary>
        public static string QuickSignInPasswordPlaceholder {
            get {
                return ResourceManager.GetString("QuickSignInPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to odzyskaj hasło.
        /// </summary>
        public static string QuickSignInRecoverPassword {
            get {
                return ResourceManager.GetString("QuickSignInRecoverPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj się.
        /// </summary>
        public static string QuickSignInSignIn {
            get {
                return ResourceManager.GetString("QuickSignInSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to załóż konto.
        /// </summary>
        public static string QuickSignUp {
            get {
                return ResourceManager.GetString("QuickSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link polecenia został już wcześniej użyty..
        /// </summary>
        public static string RecommendationAlreadyUsed {
            get {
                return ResourceManager.GetString("RecommendationAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomyślnie sprawdzono link polecenia, możesz się teraz zarejestrować jako ekspert.
        /// </summary>
        public static string RecommendationChecked {
            get {
                return ResourceManager.GetString("RecommendationChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiadomość do poleconego eksperta.
        /// </summary>
        public static string RecommendationEmailMessage {
            get {
                return ResourceManager.GetString("RecommendationEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chciałbym Cię zaprosić do systemu Asknuts jako eksperta..
        /// </summary>
        public static string RecommendationEmailMessageTemplate {
            get {
                return ResourceManager.GetString("RecommendationEmailMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dziękujemy za polecenie ekspertów. Gdy tylko zostanie Ci naliczony bonus, otrzymasz od nas email..
        /// </summary>
        public static string RecommendationFlash {
            get {
                return ResourceManager.GetString("RecommendationFlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie znaleziono linku polecenia. Upewnij się, że użyty link jest poprawny..
        /// </summary>
        public static string RecommendationNotFound {
            get {
                return ResourceManager.GetString("RecommendationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoria eksperta.
        /// </summary>
        public static string RecommendedExpertCategory {
            get {
                return ResourceManager.GetString("RecommendedExpertCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twój komentarz odnoszący się do kwalifikacji polecanego eksperta....
        /// </summary>
        public static string RecommendedExpertComment {
            get {
                return ResourceManager.GetString("RecommendedExpertComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email eksperta.
        /// </summary>
        public static string RecommendedExpertEmail {
            get {
                return ResourceManager.GetString("RecommendedExpertEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imię eksperta.
        /// </summary>
        public static string RecommendedExpertName {
            get {
                return ResourceManager.GetString("RecommendedExpertName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwisko eksperta.
        /// </summary>
        public static string RecommendedExpertSurname {
            get {
                return ResourceManager.GetString("RecommendedExpertSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twój email.
        /// </summary>
        public static string RecommenderEmail {
            get {
                return ResourceManager.GetString("RecommenderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twoje imię.
        /// </summary>
        public static string RecommenderName {
            get {
                return ResourceManager.GetString("RecommenderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twoje nazwisko.
        /// </summary>
        public static string RecommenderSurname {
            get {
                return ResourceManager.GetString("RecommenderSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane polecanego eksperta.
        /// </summary>
        public static string RecommendExpertData {
            get {
                return ResourceManager.GetString("RecommendExpertData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Znasz kogoś kto mógłby zostać ekspertem w naszym systemie? Możesz go zaprosić wypełniając powyższe pola. Wystarczy, że kompetencje tej osoby zostaną przez nas zweryfikowane i odpowie ona na pięć pytań użytkowników, a uzyskasz bonus pieniężny w wysokości 20zł..
        /// </summary>
        public static string RecommendInstructions {
            get {
                return ResourceManager.GetString("RecommendInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twoje dane.
        /// </summary>
        public static string RecommendMyData {
            get {
                return ResourceManager.GetString("RecommendMyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poleć kolejnego eksperta.
        /// </summary>
        public static string RecommendNextExpert {
            get {
                return ResourceManager.GetString("RecommendNextExpert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można znaleźć użytkownika..
        /// </summary>
        public static string ResetUserNotFound {
            get {
                return ResourceManager.GetString("ResetUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upewnij się, że użyty link do zresetowania hasła jest poprawny.
        /// </summary>
        public static string ResetUserNotFoundInstructions {
            get {
                return ResourceManager.GetString("ResetUserNotFoundInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz szczegóły.
        /// </summary>
        public static string SaveDetails {
            get {
                return ResourceManager.GetString("SaveDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz przynajmniej jedną kategorię.
        /// </summary>
        public static string SelectCategory {
            get {
                return ResourceManager.GetString("SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorie.
        /// </summary>
        public static string SelectedCategories {
            get {
                return ResourceManager.GetString("SelectedCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfiguracja wiadomości pocztowych.
        /// </summary>
        public static string SelectedMails {
            get {
                return ResourceManager.GetString("SelectedMails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zobacz szczegółowe statystyki.
        /// </summary>
        public static string ShowExpertStatistics {
            get {
                return ResourceManager.GetString("ShowExpertStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj się.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zaloguj się.
        /// </summary>
        public static string SignInLowerCase {
            get {
                return ResourceManager.GetString("SignInLowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarejestruj się.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekspert jest:.
        /// </summary>
        public static string StatusExpert {
            get {
                return ResourceManager.GetString("StatusExpert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string StatusLabel {
            get {
                return ResourceManager.GetString("StatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        public static string StatusOffline {
            get {
                return ResourceManager.GetString("StatusOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string StatusOnline {
            get {
                return ResourceManager.GetString("StatusOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dr.
        /// </summary>
        public static string TitleDoctor {
            get {
                return ResourceManager.GetString("TitleDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mgr.
        /// </summary>
        public static string TitleMaster {
            get {
                return ResourceManager.GetString("TitleMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pan.
        /// </summary>
        public static string TitleMr {
            get {
                return ResourceManager.GetString("TitleMr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prof.
        /// </summary>
        public static string TitleProfessor {
            get {
                return ResourceManager.GetString("TitleProfessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartość.
        /// </summary>
        public static string TransferValue {
            get {
                return ResourceManager.GetString("TransferValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj wartość przelewu.
        /// </summary>
        public static string TransferValueRequired {
            get {
                return ResourceManager.GetString("TransferValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przekształć je w pełne konto.
        /// </summary>
        public static string TransformTemporaryAccount {
            get {
                return ResourceManager.GetString("TransformTemporaryAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystąpił błąd. Spróbuj wprowadzić dane ponownie. Jeśli problem będzie się powtarzał, skontaktuj się z działem obsługi klienta..
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaakceptowanych pytań.
        /// </summary>
        public static string UserAcceptedQuestions {
            get {
                return ResourceManager.GetString("UserAcceptedQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadanych pytań.
        /// </summary>
        public static string UserAskedQuestions {
            get {
                return ResourceManager.GetString("UserAskedQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można znaleźć użytkownika. Upewnij się, że użyty link jest poprawny..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twoje konto eksperta nie jest jeszcze zweryfikowane. Jego weryfikacja nastąpi w ciągu 24 godzin..
        /// </summary>
        public static string VerficiationInstructions {
            get {
                return ResourceManager.GetString("VerficiationInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twoje konto jest niezweryfikowane.
        /// </summary>
        public static string VerificationNeeded {
            get {
                return ResourceManager.GetString("VerificationNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zweryfikowano następujące kompetencje eksperta:.
        /// </summary>
        public static string Verifications {
            get {
                return ResourceManager.GetString("Verifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zweryfikowany ekspert.
        /// </summary>
        public static string VerifiedExpert {
            get {
                return ResourceManager.GetString("VerifiedExpert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zweryfikowany ekspert.
        /// </summary>
        public static string VerifiedExpertCapital {
            get {
                return ResourceManager.GetString("VerifiedExpertCapital", resourceCulture);
            }
        }
    }
}
