//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Administration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Administration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Experts.Resources.App_LocalResources.Administration", typeof(Administration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik dostał przypomnienie o zaakceptowaniu lub pytaniu dalej w wątku o id {0}.
        /// </summary>
        public static string AcceptAnswerReminderEventMessage {
            get {
                return ResourceManager.GetString("AcceptAnswerReminderEventMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przypomnienie zaakceptowania pytania.
        /// </summary>
        public static string AcceptAnswerReminderEventName {
            get {
                return ResourceManager.GetString("AcceptAnswerReminderEventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer konta:.
        /// </summary>
        public static string AccountNumber {
            get {
                return ResourceManager.GetString("AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba ekspertów on-line: {0}.
        /// </summary>
        public static string ActiveExpertsStatisticsEventMessage {
            get {
                return ResourceManager.GetString("ActiveExpertsStatisticsEventMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eksperci on-line.
        /// </summary>
        public static string ActiveExpertsStatisticsEventName {
            get {
                return ResourceManager.GetString("ActiveExpertsStatisticsEventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba użytkowników on-line: {0}.
        /// </summary>
        public static string ActiveUsersStatisticsEventMessage {
            get {
                return ResourceManager.GetString("ActiveUsersStatisticsEventMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownicy on-line.
        /// </summary>
        public static string ActiveUsersStatisticsEventName {
            get {
                return ResourceManager.GetString("ActiveUsersStatisticsEventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dodaj podatrybut.
        /// </summary>
        public static string AddChildAttribute {
            get {
                return ResourceManager.GetString("AddChildAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartość usługi dla eksperta.
        /// </summary>
        public static string AdditionalServiceExpertValue {
            get {
                return ResourceManager.GetString("AdditionalServiceExpertValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik opłacił dodatkową usługę {0} w pytaniu o id {1}.
        /// </summary>
        public static string AdditionalServicePayedMessage {
            get {
                return ResourceManager.GetString("AdditionalServicePayedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opłacona dodatkowa usługa.
        /// </summary>
        public static string AdditionalServicePayedName {
            get {
                return ResourceManager.GetString("AdditionalServicePayedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cena usługi dla klienta.
        /// </summary>
        public static string AdditionalServiceUserValue {
            get {
                return ResourceManager.GetString("AdditionalServiceUserValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj nowy atrybut.
        /// </summary>
        public static string AddNewAttribute {
            get {
                return ResourceManager.GetString("AddNewAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        public static string AddNewOption {
            get {
                return ResourceManager.GetString("AddNewOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usuń.
        /// </summary>
        public static string AttributeDelete {
            get {
                return ResourceManager.GetString("AttributeDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy na pewno chcesz usunąć ten atrybut?.
        /// </summary>
        public static string AttributeDeleteConfirmation {
            get {
                return ResourceManager.GetString("AttributeDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edytuj.
        /// </summary>
        public static string AttributeEdit {
            get {
                return ResourceManager.GetString("AttributeEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autor pytania o id {0} zaakceptował odpowiedź eksperta {1}.
        /// </summary>
        public static string AuthorAcceptedAnswerMessage {
            get {
                return ResourceManager.GetString("AuthorAcceptedAnswerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akceptacja odpowiedzi.
        /// </summary>
        public static string AuthorAcceptedAnswerName {
            get {
                return ResourceManager.GetString("AuthorAcceptedAnswerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autor pytania o id {0} dodał nową wiadomość.
        /// </summary>
        public static string AuthorAddedPostMessage {
            get {
                return ResourceManager.GetString("AuthorAddedPostMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odpowiedź autora.
        /// </summary>
        public static string AuthorAddedPostName {
            get {
                return ResourceManager.GetString("AuthorAddedPostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autor pytania o id {0} ocenił wypowiedź eksperta {1}.
        /// </summary>
        public static string AuthorCreatedFeedbackMessage {
            get {
                return ResourceManager.GetString("AuthorCreatedFeedbackMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodanie oceny.
        /// </summary>
        public static string AuthorCreatedFeedbackName {
            get {
                return ResourceManager.GetString("AuthorCreatedFeedbackName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eksperci analizują wątek o id {0}.
        /// </summary>
        public static string AwaitingExpertResponseMessage {
            get {
                return ResourceManager.GetString("AwaitingExpertResponseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analizowanie pytania.
        /// </summary>
        public static string AwaitingExpertResponseName {
            get {
                return ResourceManager.GetString("AwaitingExpertResponseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik o adresie {0} zgłosił chęć przystąpienia do programu partnerskiego..
        /// </summary>
        public static string BecomePartnerRequestEventMessage {
            get {
                return ResourceManager.GetString("BecomePartnerRequestEventMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zgłoszenie do programu partnerskiego.
        /// </summary>
        public static string BecomePartnerRequestEventName {
            get {
                return ResourceManager.GetString("BecomePartnerRequestEventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wypłata środków dla eksperta.
        /// </summary>
        public static string CashPaymentEventName {
            get {
                return ResourceManager.GetString("CashPaymentEventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik o id  {0} zlecił wypłatę środków.
        /// </summary>
        public static string CashPaymentMessage {
            get {
                return ResourceManager.GetString("CashPaymentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Długość tytułu pytania w katalogu nie może przekroczyć 60 znaków.
        /// </summary>
        public static string CatalogSanitizedThreadTitleTooLong {
            get {
                return ResourceManager.GetString("CatalogSanitizedThreadTitleTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tytuł pytania w katalogu.
        /// </summary>
        public static string CatalogThreadTitle {
            get {
                return ResourceManager.GetString("CatalogThreadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dostępne opcje.
        /// </summary>
        public static string CategoryAttributeAvailableOptions {
            get {
                return ResourceManager.GetString("CategoryAttributeAvailableOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atrybut został dodany poprawnie..
        /// </summary>
        public static string CategoryAttributeCreated {
            get {
                return ResourceManager.GetString("CategoryAttributeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atrybut został usunięty.
        /// </summary>
        public static string CategoryAttributeDeleted {
            get {
                return ResourceManager.GetString("CategoryAttributeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waga przy dopasowaniu.
        /// </summary>
        public static string CategoryAttributeImportance {
            get {
                return ResourceManager.GetString("CategoryAttributeImportance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj wagę atrybutu.
        /// </summary>
        public static string CategoryAttributeImportanceRequired {
            get {
                return ResourceManager.GetString("CategoryAttributeImportanceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa.
        /// </summary>
        public static string CategoryAttributeName {
            get {
                return ResourceManager.GetString("CategoryAttributeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa atrybutu jest wymagana.
        /// </summary>
        public static string CategoryAttributeNameRequired {
            get {
                return ResourceManager.GetString("CategoryAttributeNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy na pewno chcesz usunąć tą opcję?.
        /// </summary>
        public static string CategoryAttributeOptionDeleteConfirmation {
            get {
                return ResourceManager.GetString("CategoryAttributeOptionDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nazwa.
        /// </summary>
        public static string CategoryAttributeOptionName {
            get {
                return ResourceManager.GetString("CategoryAttributeOptionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modyfikator ceny.
        /// </summary>
        public static string CategoryAttributeOptionPriceModifier {
            get {
                return ResourceManager.GetString("CategoryAttributeOptionPriceModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dostępne opcje.
        /// </summary>
        public static string CategoryAttributeOptions {
            get {
                return ResourceManager.GetString("CategoryAttributeOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atrybuty kategorii:.
        /// </summary>
        public static string CategoryAttributes {
            get {
                return ResourceManager.GetString("CategoryAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ atrybutu.
        /// </summary>
        public static string CategoryAttributeType {
            get {
                return ResourceManager.GetString("CategoryAttributeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Długi tekst.
        /// </summary>
        public static string CategoryAttributeTypeMultiLineText {
            get {
                return ResourceManager.GetString("CategoryAttributeTypeMultiLineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wielokrotny wybór.
        /// </summary>
        public static string CategoryAttributeTypeMultiSelect {
            get {
                return ResourceManager.GetString("CategoryAttributeTypeMultiSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krótki tekst.
        /// </summary>
        public static string CategoryAttributeTypeSingleLineText {
            get {
                return ResourceManager.GetString("CategoryAttributeTypeSingleLineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pojedynczy wybór.
        /// </summary>
        public static string CategoryAttributeTypeSingleSelect {
            get {
                return ResourceManager.GetString("CategoryAttributeTypeSingleSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atrybut został zaktualizowany..
        /// </summary>
        public static string CategoryAttributeUpdated {
            get {
                return ResourceManager.GetString("CategoryAttributeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista kategorii.
        /// </summary>
        public static string CategoryList {
            get {
                return ResourceManager.GetString("CategoryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czat nr {0} został zamknięty.
        /// </summary>
        public static string ChatClosedInfo {
            get {
                return ResourceManager.GetString("ChatClosedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czat nr {0} został zamknięty. Do użytkownika zostało wysłane podsumowanie rozmowy.
        /// </summary>
        public static string ChatClosedSummarySentInfo {
            get {
                return ResourceManager.GetString("ChatClosedSummarySentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utworzono.
        /// </summary>
        public static string ChatCreationDateColumn {
            get {
                return ResourceManager.GetString("ChatCreationDateColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autor.
        /// </summary>
        public static string ChatDetailsAuthorColumn {
            get {
                return ResourceManager.GetString("ChatDetailsAuthorColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utworzono.
        /// </summary>
        public static string ChatDetailsCreationDateColumn {
            get {
                return ResourceManager.GetString("ChatDetailsCreationDateColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wróć do wszystkich wiadomości.
        /// </summary>
        public static string ChatDetailsReturnToChatOverview {
            get {
                return ResourceManager.GetString("ChatDetailsReturnToChatOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiadomość.
        /// </summary>
        public static string ChatDetailsTextColumn {
            get {
                return ResourceManager.GetString("ChatDetailsTextColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napisz wiadomość.
        /// </summary>
        public static string ChatDetailsWriteMessage {
            get {
                return ResourceManager.GetString("ChatDetailsWriteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string ChatIdColumn {
            get {
                return ResourceManager.GetString("ChatIdColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ostatnia wypowiedź.
        /// </summary>
        public static string ChatLastModificationDateColumn {
            get {
                return ResourceManager.GetString("ChatLastModificationDateColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderator prowadzący.
        /// </summary>
        public static string ChatModeratorColumn {
            get {
                return ResourceManager.GetString("ChatModeratorColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiadomości.
        /// </summary>
        public static string ChatNoOfMassegesColumn {
            get {
                return ResourceManager.GetString("ChatNoOfMassegesColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pytania historyczne.
        /// </summary>
        public static string ChatOverviewClosedTitle {
            get {
                return ResourceManager.GetString("ChatOverviewClosedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pytania oczekujące Twojej odpowiedzi.
        /// </summary>
        public static string ChatOverviewWaitingForResponseTitle {
            get {
                return ResourceManager.GetString("ChatOverviewWaitingForResponseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pytający.
        /// </summary>
        public static string ChatsOwnerColumn {
            get {
                return ResourceManager.GetString("ChatsOwnerColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiadomości klientów.
        /// </summary>
        public static string ClientMessages {
            get {
                return ResourceManager.GetString("ClientMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj atrybut.
        /// </summary>
        public static string CreateCategoryAttribute {
            get {
                return ResourceManager.GetString("CreateCategoryAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekspert {0} poprosił o szczegóły autora pytania o id {1}.
        /// </summary>
        public static string DetailsRequestEventMessage {
            get {
                return ResourceManager.GetString("DetailsRequestEventMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prośba o szczegóły.
        /// </summary>
        public static string DetailsRequestEventName {
            get {
                return ResourceManager.GetString("DetailsRequestEventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak sprecyzowanych kompetencji.
        /// </summary>
        public static string EmptyExpertCompetence {
            get {
                return ResourceManager.GetString("EmptyExpertCompetence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiadomość.
        /// </summary>
        public static string EventMessage {
            get {
                return ResourceManager.GetString("EventMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zdarzenie.
        /// </summary>
        public static string EventName {
            get {
                return ResourceManager.GetString("EventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string EventOccurenceDate {
            get {
                return ResourceManager.GetString("EventOccurenceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zdarzenia.
        /// </summary>
        public static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekspert.
        /// </summary>
        public static string Expert {
            get {
                return ResourceManager.GetString("Expert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekspert {0} skomentował ocene użytkownika na odpowiedź pytania o id {1}.
        /// </summary>
        public static string ExpertCommentedFeedbackEventMessage {
            get {
                return ResourceManager.GetString("ExpertCommentedFeedbackEventMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komentarz oceny eksperta.
        /// </summary>
        public static string ExpertCommentedFeedbackEventName {
            get {
                return ResourceManager.GetString("ExpertCommentedFeedbackEventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kompetecje eksperta:.
        /// </summary>
        public static string ExpertCompetence {
            get {
                return ResourceManager.GetString("ExpertCompetence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekspert {0} zaproponował cenę dla wątku o id {1}.
        /// </summary>
        public static string ExpertPriceProposalMessage {
            get {
                return ResourceManager.GetString("ExpertPriceProposalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propozycja ceny.
        /// </summary>
        public static string ExpertPriceProposalName {
            get {
                return ResourceManager.GetString("ExpertPriceProposalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekspert {0} zaproponował dodatkową usługę dla wątku o id {1}.
        /// </summary>
        public static string ExpertProposedAdditionalService {
            get {
                return ResourceManager.GetString("ExpertProposedAdditionalService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekspert {0} zmienił dane publiczne.
        /// </summary>
        public static string ExpertPublicDataChangedMessage {
            get {
                return ResourceManager.GetString("ExpertPublicDataChangedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmiana danych publicznych.
        /// </summary>
        public static string ExpertPublicDataChangedName {
            get {
                return ResourceManager.GetString("ExpertPublicDataChangedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekspert o nazwie {0} wymaga zweryfikowania jego kwalifikacji. Zmiany.
        /// </summary>
        public static string ExpertQualificationsChangedEventMessage {
            get {
                return ResourceManager.GetString("ExpertQualificationsChangedEventMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmiana kwalifikacji eksperta.
        /// </summary>
        public static string ExpertQualificationsChangedEventName {
            get {
                return ResourceManager.GetString("ExpertQualificationsChangedEventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekspert o nazwie {0} i adresie {1} zarejestrował się z id = {2}.
        /// </summary>
        public static string ExpertRegisteredEventMessage {
            get {
                return ResourceManager.GetString("ExpertRegisteredEventMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejestracja eksperta.
        /// </summary>
        public static string ExpertRegisteredEventName {
            get {
                return ResourceManager.GetString("ExpertRegisteredEventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powiadomiono {0} ekspertów o wątku o id {1} .
        /// </summary>
        public static string ExpertThreadNotifiedEventMessage {
            get {
                return ResourceManager.GetString("ExpertThreadNotifiedEventMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powiadomiono ekspertów.
        /// </summary>
        public static string ExpertThreadNotifiedEventName {
            get {
                return ResourceManager.GetString("ExpertThreadNotifiedEventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widget został wygenerowany przez eksperta {0}.
        /// </summary>
        public static string ExpertWidgetGeneratedEventMessage {
            get {
                return ResourceManager.GetString("ExpertWidgetGeneratedEventMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wygenerowano widget eksperta.
        /// </summary>
        public static string ExpertWidgetGeneratedEventName {
            get {
                return ResourceManager.GetString("ExpertWidgetGeneratedEventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propozycja usługi dodatkowej w wątku {0}.
        /// </summary>
        public static string ExtraServiceProposalEventMessage {
            get {
                return ResourceManager.GetString("ExtraServiceProposalEventMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propozycja usługi.
        /// </summary>
        public static string ExtraServiceProposalEventName {
            get {
                return ResourceManager.GetString("ExtraServiceProposalEventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekspert {0} zrezygnował z odpowiedzi na pytanie o id {1}.
        /// </summary>
        public static string GiveUpEventMessage {
            get {
                return ResourceManager.GetString("GiveUpEventMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezygnacja z pytania.
        /// </summary>
        public static string GiveUpEventName {
            get {
                return ResourceManager.GetString("GiveUpEventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderuj słowo kluczowe.
        /// </summary>
        public static string KeywordModeration {
            get {
                return ResourceManager.GetString("KeywordModeration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dnia {0} zadano {1} pytań.
        /// </summary>
        public static string LastDayThreadsStatisticsEventMessage {
            get {
                return ResourceManager.GetString("LastDayThreadsStatisticsEventMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba zadanych pytań.
        /// </summary>
        public static string LastDayThreadsStatisticsEventName {
            get {
                return ResourceManager.GetString("LastDayThreadsStatisticsEventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik dostał propozycję dodatkowej usługi od eksperta {0} w pytaniu o id {1}.
        /// </summary>
        public static string NewAdditionalServiceEventMessage {
            get {
                return ResourceManager.GetString("NewAdditionalServiceEventMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowa dodatkowa usługa.
        /// </summary>
        public static string NewAdditionalServiceEventName {
            get {
                return ResourceManager.GetString("NewAdditionalServiceEventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik o id {0} rozpoczął rozmowę chat.
        /// </summary>
        public static string NewChatEventMessage {
            get {
                return ResourceManager.GetString("NewChatEventMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowa wiadomość chat.
        /// </summary>
        public static string NewChatEventName {
            get {
                return ResourceManager.GetString("NewChatEventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba słów kluczowych oczekujących na weryfikację: {0}.
        /// </summary>
        public static string NewSeoKeywordsStatisticsEventMessage {
            get {
                return ResourceManager.GetString("NewSeoKeywordsStatisticsEventMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Słowa kluczowe do weryfikacji.
        /// </summary>
        public static string NewSeoKeywordsStatisticsEventName {
            get {
                return ResourceManager.GetString("NewSeoKeywordsStatisticsEventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wątek o id {0} został stworzony. Wartości prowizji: {1}.
        /// </summary>
        public static string NewThreadEventMessage {
            get {
                return ResourceManager.GetString("NewThreadEventMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowy wątek.
        /// </summary>
        public static string NewThreadEventName {
            get {
                return ResourceManager.GetString("NewThreadEventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadano nowe pytanie ekspertowi {0}.
        /// </summary>
        public static string NewThreadForExpertEventMessage {
            get {
                return ResourceManager.GetString("NewThreadForExpertEventMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowe pytanie do eksperta.
        /// </summary>
        public static string NewThreadForExpertEventName {
            get {
                return ResourceManager.GetString("NewThreadForExpertEventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nikt nie udzielił odpowiedzi na pytanie wątku o id {0} w przeciągu 24h.
        /// </summary>
        public static string NoAnswerEventMessage {
            get {
                return ResourceManager.GetString("NoAnswerEventMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak odpowiedzi.
        /// </summary>
        public static string NoAnswerEventName {
            get {
                return ResourceManager.GetString("NoAnswerEventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak opcji.
        /// </summary>
        public static string NoCategoryAttributeOptions {
            get {
                return ResourceManager.GetString("NoCategoryAttributeOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner.
        /// </summary>
        public static string Partner {
            get {
                return ResourceManager.GetString("Partner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wypłata środków dla partnera.
        /// </summary>
        public static string PartnerCashPaymentEventName {
            get {
                return ResourceManager.GetString("PartnerCashPaymentEventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner o id {0} zlecił wypłatę środków.
        /// </summary>
        public static string PartnerCashPaymentMessage {
            get {
                return ResourceManager.GetString("PartnerCashPaymentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiadomość z bilansem została wysłana do partnera o id: {0}.
        /// </summary>
        public static string PartnerStatisticsEmailSentEventMessage {
            get {
                return ResourceManager.GetString("PartnerStatisticsEmailSentEventMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wysłano bilans partnera.
        /// </summary>
        public static string PartnerStatisticsEmailSentEventName {
            get {
                return ResourceManager.GetString("PartnerStatisticsEmailSentEventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Płatność za {0} w wątku o id {1} się nie powiodła.
        /// </summary>
        public static string PaymentFailedEventMessage {
            get {
                return ResourceManager.GetString("PaymentFailedEventMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Płatność się nie powiodła.
        /// </summary>
        public static string PaymentFailedEventName {
            get {
                return ResourceManager.GetString("PaymentFailedEventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik zaakceptował propozycję nowej ceny dla wątku {0} od eksperta {1} .
        /// </summary>
        public static string PriceProposalAcceptedEventMessage {
            get {
                return ResourceManager.GetString("PriceProposalAcceptedEventMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akceptacja wyższej ceny.
        /// </summary>
        public static string PriceProposalAcceptedEventName {
            get {
                return ResourceManager.GetString("PriceProposalAcceptedEventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekspert {0} udzielił odpowiedzi na pytanie o id {1}.
        /// </summary>
        public static string QuestionAnsweredEventMessage {
            get {
                return ResourceManager.GetString("QuestionAnsweredEventMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odpowiedź na pytanie.
        /// </summary>
        public static string QuestionAnsweredEventName {
            get {
                return ResourceManager.GetString("QuestionAnsweredEventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderacja pytań.
        /// </summary>
        public static string QuestionModeration {
            get {
                return ResourceManager.GetString("QuestionModeration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czyszczenie pytań.
        /// </summary>
        public static string SanitizationListModeration {
            get {
                return ResourceManager.GetString("SanitizationListModeration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string SanitizationStatus {
            get {
                return ResourceManager.GetString("SanitizationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krytyczny problem.
        /// </summary>
        public static string SystemBreakdownEvent {
            get {
                return ResourceManager.GetString("SystemBreakdownEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd systemu.
        /// </summary>
        public static string SystemFailureEventName {
            get {
                return ResourceManager.GetString("SystemFailureEventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak zdarzeń.
        /// </summary>
        public static string ThereIsNoEvents {
            get {
                return ResourceManager.GetString("ThereIsNoEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wątek o id {0} został zamknięty.
        /// </summary>
        public static string ThreadClosedEventMessage {
            get {
                return ResourceManager.GetString("ThreadClosedEventMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wątek zamknięty.
        /// </summary>
        public static string ThreadClosedEventName {
            get {
                return ResourceManager.GetString("ThreadClosedEventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uwaga do wątku o id {0}: {1}.
        /// </summary>
        public static string ThreadIssueReportEventMessage {
            get {
                return ResourceManager.GetString("ThreadIssueReportEventMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem z pytaniem.
        /// </summary>
        public static string ThreadIssueReportEventName {
            get {
                return ResourceManager.GetString("ThreadIssueReportEventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wątek &quot;{0}&quot; został przejęty przez eksperta {1}.
        /// </summary>
        public static string ThreadOccupiedEventMessage {
            get {
                return ResourceManager.GetString("ThreadOccupiedEventMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wątek przejęty.
        /// </summary>
        public static string ThreadOccupiedEventName {
            get {
                return ResourceManager.GetString("ThreadOccupiedEventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wątek o id {0} został opłacony.
        /// </summary>
        public static string ThreadPayedEventMessage {
            get {
                return ResourceManager.GetString("ThreadPayedEventMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opłacono wątek.
        /// </summary>
        public static string ThreadPayedEventName {
            get {
                return ResourceManager.GetString("ThreadPayedEventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wątek &quot;{0}&quot; został zwolniony przez eksperta {1}.
        /// </summary>
        public static string ThreadReleasedEventMessage {
            get {
                return ResourceManager.GetString("ThreadReleasedEventMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wątek zwolniony.
        /// </summary>
        public static string ThreadReleasedEventName {
            get {
                return ResourceManager.GetString("ThreadReleasedEventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane transferu:.
        /// </summary>
        public static string TransferData {
            get {
                return ResourceManager.GetString("TransferData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data zlecenia:.
        /// </summary>
        public static string TransferDate {
            get {
                return ResourceManager.GetString("TransferDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zlecił:.
        /// </summary>
        public static string TransferOrdered {
            get {
                return ResourceManager.GetString("TransferOrdered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tytuł:.
        /// </summary>
        public static string TransferTitle {
            get {
                return ResourceManager.GetString("TransferTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartość zlecenia:.
        /// </summary>
        public static string TransferValue {
            get {
                return ResourceManager.GetString("TransferValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz.
        /// </summary>
        public static string UpdateCategoryAttribute {
            get {
                return ResourceManager.GetString("UpdateCategoryAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz.
        /// </summary>
        public static string UpdateCategoryAttributeOption {
            get {
                return ResourceManager.GetString("UpdateCategoryAttributeOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik o adresie {0} i id = {1} aktywował konto.
        /// </summary>
        public static string UserAccountActivatedEventMessage {
            get {
                return ResourceManager.GetString("UserAccountActivatedEventMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktywacja użytkownika.
        /// </summary>
        public static string UserAccountActivatedEventName {
            get {
                return ResourceManager.GetString("UserAccountActivatedEventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik o id {0} zmienił swój adres email na {1}.
        /// </summary>
        public static string UserChangedEmailEventMessage {
            get {
                return ResourceManager.GetString("UserChangedEmailEventMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmiana adresu email.
        /// </summary>
        public static string UserChangedEmailEventName {
            get {
                return ResourceManager.GetString("UserChangedEmailEventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik o id {0} zmienił swoje hasło.
        /// </summary>
        public static string UserChangedPasswordEventMessage {
            get {
                return ResourceManager.GetString("UserChangedPasswordEventMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmiana hasła.
        /// </summary>
        public static string UserChangedPasswordEventName {
            get {
                return ResourceManager.GetString("UserChangedPasswordEventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data rejestracji.
        /// </summary>
        public static string UserCreationDate {
            get {
                return ResourceManager.GetString("UserCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik stworzył pytanie z niestandardową ceną w wątku o id {0}.
        /// </summary>
        public static string UserDefinedPriceEventMessage {
            get {
                return ResourceManager.GetString("UserDefinedPriceEventMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niestandardowa cena dla wątku.
        /// </summary>
        public static string UserDefinedPriceEventName {
            get {
                return ResourceManager.GetString("UserDefinedPriceEventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string UserEmail {
            get {
                return ResourceManager.GetString("UserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak użytkowników.
        /// </summary>
        public static string UserGridEmptyText {
            get {
                return ResourceManager.GetString("UserGridEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista użytkowników.
        /// </summary>
        public static string UserList {
            get {
                return ResourceManager.GetString("UserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarządzaj użytkownikami.
        /// </summary>
        public static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wypłata środków.
        /// </summary>
        public static string UserPayoff {
            get {
                return ResourceManager.GetString("UserPayoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wypłacona kwota.
        /// </summary>
        public static string UserPayoffAmount {
            get {
                return ResourceManager.GetString("UserPayoffAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj kwotę.
        /// </summary>
        public static string UserPayoffAmountRequired {
            get {
                return ResourceManager.GetString("UserPayoffAmountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kwota przekracza wartość konta użytkownika.
        /// </summary>
        public static string UserPayoffAmountTooHigh {
            get {
                return ResourceManager.GetString("UserPayoffAmountTooHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komentarz.
        /// </summary>
        public static string UserPayoffComment {
            get {
                return ResourceManager.GetString("UserPayoffComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zgłoś wypłatę.
        /// </summary>
        public static string UserPayoffSaveButton {
            get {
                return ResourceManager.GetString("UserPayoffSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wypłata środków została zgłoszona.
        /// </summary>
        public static string UserPayoffSuccessful {
            get {
                return ResourceManager.GetString("UserPayoffSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wypłata środków użytkownika.
        /// </summary>
        public static string UserPayoffTitle {
            get {
                return ResourceManager.GetString("UserPayoffTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik o adresie {0} zarejestrował się z id = {1}.
        /// </summary>
        public static string UserRegisteredEventMessage {
            get {
                return ResourceManager.GetString("UserRegisteredEventMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejestracja użytkownika.
        /// </summary>
        public static string UserRegisteredEventName {
            get {
                return ResourceManager.GetString("UserRegisteredEventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik zarządał wypłaty środków.
        /// </summary>
        public static string UserRequestedPayoff {
            get {
                return ResourceManager.GetString("UserRequestedPayoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tak.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
