//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmailConfigurations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailConfigurations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Experts.Resources.App_LocalResources.EmailConfigurations", typeof(EmailConfigurations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przypomnienie o akceptacji pytania.
        /// </summary>
        public static string EmailTypeAcceptAnswerReminder {
            get {
                return ResourceManager.GetString("EmailTypeAcceptAnswerReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decyzje użytkowników o dodatkowych usługach.
        /// </summary>
        public static string EmailTypeAdditionalServiceAnswerEmail {
            get {
                return ResourceManager.GetString("EmailTypeAdditionalServiceAnswerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodatkowe usługi od ekspertów.
        /// </summary>
        public static string EmailTypeAdditionalServiceEmail {
            get {
                return ResourceManager.GetString("EmailTypeAdditionalServiceEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opóźnienia w odpowiedzi na pytanie.
        /// </summary>
        public static string EmailTypeAwaitingExpertResponseEmail {
            get {
                return ResourceManager.GetString("EmailTypeAwaitingExpertResponseEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potwierdzenie e-maila.
        /// </summary>
        public static string EmailTypeConfirmationEmail {
            get {
                return ResourceManager.GetString("EmailTypeConfirmationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowe bezpośrednie pytanie od użytkownika.
        /// </summary>
        public static string EmailTypeDirectQuestionEmail {
            get {
                return ResourceManager.GetString("EmailTypeDirectQuestionEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miesięczne podsumowanie statystyk eksperta.
        /// </summary>
        public static string EmailTypeExpertStatisticsEmail {
            get {
                return ResourceManager.GetString("EmailTypeExpertStatisticsEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komentarz do opinii na temat eksperta.
        /// </summary>
        public static string EmailTypeFeedbackCommentEmail {
            get {
                return ResourceManager.GetString("EmailTypeFeedbackCommentEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zrezygnowanie eksperta z odpowiedzi.
        /// </summary>
        public static string EmailTypeGiveUpEmail {
            get {
                return ResourceManager.GetString("EmailTypeGiveUpEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przypomnienie o zadawaniu pytań.
        /// </summary>
        public static string EmailTypeMonthlyAskEncouragement {
            get {
                return ResourceManager.GetString("EmailTypeMonthlyAskEncouragement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowe pytanie w twojej kategorii.
        /// </summary>
        public static string EmailTypeNewInterestingThreadEmail {
            get {
                return ResourceManager.GetString("EmailTypeNewInterestingThreadEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowa wiadomość od moderatora w pytaniu, na które odpowiadasz.
        /// </summary>
        public static string EmailTypeNewModeratorPostExpertEmail {
            get {
                return ResourceManager.GetString("EmailTypeNewModeratorPostExpertEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowa wiadomość od moderatora.
        /// </summary>
        public static string EmailTypeNewModeratorPostUserEmail {
            get {
                return ResourceManager.GetString("EmailTypeNewModeratorPostUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowa prywatna wiadomość od moderatora.
        /// </summary>
        public static string EmailTypeNewPMToExpertEmail {
            get {
                return ResourceManager.GetString("EmailTypeNewPMToExpertEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newsletter.
        /// </summary>
        public static string EmailTypeNewsletter {
            get {
                return ResourceManager.GetString("EmailTypeNewsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak odpowiedzi na pytanie.
        /// </summary>
        public static string EmailTypeNoExpertResponse {
            get {
                return ResourceManager.GetString("EmailTypeNoExpertResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przejęcie pytania przez eksperta.
        /// </summary>
        public static string EmailTypeOccupyThreadEmail {
            get {
                return ResourceManager.GetString("EmailTypeOccupyThreadEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacja o przystąpieniu do programu partnerskiego.
        /// </summary>
        public static string EmailTypePartnerAcceptedEmail {
            get {
                return ResourceManager.GetString("EmailTypePartnerAcceptedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odrzucenie prośby o przystąpienie do programu partnerskiego.
        /// </summary>
        public static string EmailTypePartnerRejectedEmail {
            get {
                return ResourceManager.GetString("EmailTypePartnerRejectedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miesięczne podsumowanie statystyk partnera.
        /// </summary>
        public static string EmailTypePartnerStatisticsEmail {
            get {
                return ResourceManager.GetString("EmailTypePartnerStatisticsEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odpowiedź na propozycję ceny.
        /// </summary>
        public static string EmailTypePaymentAnswerEmail {
            get {
                return ResourceManager.GetString("EmailTypePaymentAnswerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowa cena za pytanie zaakceptowana.
        /// </summary>
        public static string EmailTypePriceProposalAcceptedEmail {
            get {
                return ResourceManager.GetString("EmailTypePriceProposalAcceptedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowa propozycja ceny przez eksperta.
        /// </summary>
        public static string EmailTypePriceProposalEmail {
            get {
                return ResourceManager.GetString("EmailTypePriceProposalEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zgłoszenie problemu z pytaniem.
        /// </summary>
        public static string EmailTypeReportIssueEmail {
            get {
                return ResourceManager.GetString("EmailTypeReportIssueEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potwierdzenie zaakceptowania odpowiedzi.
        /// </summary>
        public static string EmailTypeThreadAnswerAcceptedEmail {
            get {
                return ResourceManager.GetString("EmailTypeThreadAnswerAcceptedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odpowiedź eksperta na pytanie.
        /// </summary>
        public static string EmailTypeThreadAnsweredEmail {
            get {
                return ResourceManager.GetString("EmailTypeThreadAnsweredEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expert dodał załącznik.
        /// </summary>
        public static string EmailTypeThreadExpertAddAttachmentEmail {
            get {
                return ResourceManager.GetString("EmailTypeThreadExpertAddAttachmentEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komentarz eksperta do pytania.
        /// </summary>
        public static string EmailTypeThreadExpertCommentEmail {
            get {
                return ResourceManager.GetString("EmailTypeThreadExpertCommentEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prośba o więcej szczegółów w pytaniu.
        /// </summary>
        public static string EmailTypeThreadMoreDetailsEmail {
            get {
                return ResourceManager.GetString("EmailTypeThreadMoreDetailsEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowa wiadomość od użytkownika.
        /// </summary>
        public static string EmailTypeThreadNewPostEmailToExpert {
            get {
                return ResourceManager.GetString("EmailTypeThreadNewPostEmailToExpert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowa wiadomość od eksperta.
        /// </summary>
        public static string EmailTypeThreadNewPostEmailToUser {
            get {
                return ResourceManager.GetString("EmailTypeThreadNewPostEmailToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowa wiadomość w pytaniu.
        /// </summary>
        public static string EmailTypeThreadNewPostToExpertEmail {
            get {
                return ResourceManager.GetString("EmailTypeThreadNewPostToExpertEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik dodał załącznik.
        /// </summary>
        public static string EmailTypeThreadUserAddAttachmentEmail {
            get {
                return ResourceManager.GetString("EmailTypeThreadUserAddAttachmentEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potwierdzenie wypłaty środków.
        /// </summary>
        public static string EmailTypeUserPayoffConfirmationEmail {
            get {
                return ResourceManager.GetString("EmailTypeUserPayoffConfirmationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otrzymywane wiadomości pocztowe.
        /// </summary>
        public static string MenuEmailConfigurations {
            get {
                return ResourceManager.GetString("MenuEmailConfigurations", resourceCulture);
            }
        }
    }
}
