//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Experts.Resources.App_LocalResources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nas.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odpowiadam.
        /// </summary>
        public static string AnsweringQuestionList {
            get {
                return ResourceManager.GetString("AnsweringQuestionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pytam.
        /// </summary>
        public static string AskingQuestionList {
            get {
                return ResourceManager.GetString("AskingQuestionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AskNuts.com.
        /// </summary>
        public static string AskNutsCom {
            get {
                return ResourceManager.GetString("AskNutsCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powrót do strony głównej.
        /// </summary>
        public static string BackToHome {
            get {
                return ResourceManager.GetString("BackToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilans.
        /// </summary>
        public static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zostań ekspertem.
        /// </summary>
        public static string BecomeExpert {
            get {
                return ResourceManager.GetString("BecomeExpert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak rozpoczętych czatów.
        /// </summary>
        public static string ChatEmptyGrid {
            get {
                return ResourceManager.GetString("ChatEmptyGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiadomości klientów.
        /// </summary>
        public static string ChatsOverview {
            get {
                return ResourceManager.GetString("ChatsOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opinie.
        /// </summary>
        public static string CommentsList {
            get {
                return ResourceManager.GetString("CommentsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy na pewno?.
        /// </summary>
        public static string ConfirmationMessage {
            get {
                return ResourceManager.GetString("ConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konsultant.
        /// </summary>
        public static string Consultant {
            get {
                return ResourceManager.GetString("Consultant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kontakt@asknuts.com.
        /// </summary>
        public static string ContactMail {
            get {
                return ResourceManager.GetString("ContactMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (c) 2012 by Gorrion, Massachusetts.
        /// </summary>
        public static string CopyrightNote {
            get {
                return ResourceManager.GetString("CopyrightNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadaj pytanie.
        /// </summary>
        public static string CreateThread {
            get {
                return ResourceManager.GetString("CreateThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zł.
        /// </summary>
        public static string CurrencyPLN {
            get {
                return ResourceManager.GetString("CurrencyPLN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dni temu.
        /// </summary>
        public static string DateDaysAgo {
            get {
                return ResourceManager.GetString("DateDaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd.MM.yyyy.
        /// </summary>
        public static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to godz temu.
        /// </summary>
        public static string DateHoursAgo {
            get {
                return ResourceManager.GetString("DateHoursAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min temu.
        /// </summary>
        public static string DateMinutesAgo {
            get {
                return ResourceManager.GetString("DateMinutesAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s temu.
        /// </summary>
        public static string DateOneSecondAgo {
            get {
                return ResourceManager.GetString("DateOneSecondAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s temu.
        /// </summary>
        public static string DateSecondsAgo {
            get {
                return ResourceManager.GetString("DateSecondsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dziękujemy za informację o problemie. Postaramy się go naprawić tak szybko, jak to tylko możliwe..
        /// </summary>
        public static string ErrorFormConfirmation {
            get {
                return ResourceManager.GetString("ErrorFormConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nasz serwis jest wciąż testowany i udoskonalany, stąd zapewne cała heca. Możesz nam jednak pomóc wypełniając informację o okolicznościach wystąpienia tego błędu. Postaramy się poinformować Cię gdy zostanie on naprawiony. Za utrudnienia przepraszamy i dziękujemy za wszelką pomoc!.
        /// </summary>
        public static string ErrorFormDescription {
            get {
                return ResourceManager.GetString("ErrorFormDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okoliczności wystąpienia błędu.
        /// </summary>
        public static string ErrorFormDescriptionLabel {
            get {
                return ResourceManager.GetString("ErrorFormDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twój adres e-mail.
        /// </summary>
        public static string ErrorFormEmailLabel {
            get {
                return ResourceManager.GetString("ErrorFormEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zgłoszenie użytkownika: {0}
        ///E-mail użytkownika: {1}
        ///
        ///.
        /// </summary>
        public static string ErrorFormMessageTemplate {
            get {
                return ResourceManager.GetString("ErrorFormMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyślij.
        /// </summary>
        public static string ErrorFormSubmit {
            get {
                return ResourceManager.GetString("ErrorFormSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przepraszamy, wystąpił błąd aplikacji.
        /// </summary>
        public static string ErrorFormTitle {
            get {
                return ResourceManager.GetString("ErrorFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dziennik zdarzeń.
        /// </summary>
        public static string EventsList {
            get {
                return ResourceManager.GetString("EventsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekspert FAQ.
        /// </summary>
        public static string ExpertFAQ {
            get {
                return ResourceManager.GetString("ExpertFAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dla ekspertów.
        /// </summary>
        public static string ExpertHelp {
            get {
                return ResourceManager.GetString("ExpertHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie zostałeś jeszcze zweryfikowany jako ekspert. Skontaktujemy się z Tobą w najbliższym czasie, aby dokonać weryfikacji..
        /// </summary>
        public static string ExpertIsNotVerifiedInfo {
            get {
                return ResourceManager.GetString("ExpertIsNotVerifiedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zostałeś zweryfikowany jako ekspert..
        /// </summary>
        public static string ExpertIsVerifiedInfo {
            get {
                return ResourceManager.GetString("ExpertIsVerifiedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publiczny profil.
        /// </summary>
        public static string ExpertPublicProfile {
            get {
                return ResourceManager.GetString("ExpertPublicProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eksperci.
        /// </summary>
        public static string Experts {
            get {
                return ResourceManager.GetString("Experts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poszukujemy ekspertów.
        /// </summary>
        public static string ExpertSearch {
            get {
                return ResourceManager.GetString("ExpertSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak pytań.
        /// </summary>
        public static string GridEmptyText {
            get {
                return ResourceManager.GetString("GridEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomoc.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jak to działa?.
        /// </summary>
        public static string HowItWorks {
            get {
                return ResourceManager.GetString("HowItWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacje.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katalog odpowiedzi.
        /// </summary>
        public static string KeywordListAnswers {
            get {
                return ResourceManager.GetString("KeywordListAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popularni eksperci.
        /// </summary>
        public static string KeywordListExperts {
            get {
                return ResourceManager.GetString("KeywordListExperts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popularne frazy.
        /// </summary>
        public static string KeywordListPhrases {
            get {
                return ResourceManager.GetString("KeywordListPhrases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popularne tematy pytań.
        /// </summary>
        public static string KeywordListQuestions {
            get {
                return ResourceManager.GetString("KeywordListQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Słowa kluczowe.
        /// </summary>
        public static string KeywordsModeration {
            get {
                return ResourceManager.GetString("KeywordsModeration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baza wiedzy.
        /// </summary>
        public static string KnowledgeBase {
            get {
                return ResourceManager.GetString("KnowledgeBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Najnowsze informacje z bloga.
        /// </summary>
        public static string LatestNews {
            get {
                return ResourceManager.GetString("LatestNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poznaj AskNuts!.
        /// </summary>
        public static string MeetAsknuts {
            get {
                return ResourceManager.GetString("MeetAsknuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadaj pytanie zaufanym ekspertom i uzyskaj najlepszą odpowiedź. Gwarancja 100% satysfakcji..
        /// </summary>
        public static string MeetAsknutsHint {
            get {
                return ResourceManager.GetString("MeetAsknutsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dowiedz się więcej....
        /// </summary>
        public static string MeetAsknutsHintMoreButton {
            get {
                return ResourceManager.GetString("MeetAsknutsHintMoreButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderacja.
        /// </summary>
        public static string ModerationSection {
            get {
                return ResourceManager.GetString("ModerationSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moje konto.
        /// </summary>
        public static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moje pytania.
        /// </summary>
        public static string MyQuestionsSection {
            get {
                return ResourceManager.GetString("MyQuestionsSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadaj nowe pytanie.
        /// </summary>
        public static string NewQuestion {
            get {
                return ResourceManager.GetString("NewQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korzystasz z konta anonimowego.
        /// </summary>
        public static string NoSignUpUserWelcome {
            get {
                return ResourceManager.GetString("NoSignUpUserWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pierwszy.
        /// </summary>
        public static string PagerFirst {
            get {
                return ResourceManager.GetString("PagerFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ostatni .
        /// </summary>
        public static string PagerLast {
            get {
                return ResourceManager.GetString("PagerLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to następny ».
        /// </summary>
        public static string PagerNext {
            get {
                return ResourceManager.GetString("PagerNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to « poprzedni.
        /// </summary>
        public static string PagerPrevious {
            get {
                return ResourceManager.GetString("PagerPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Współpraca.
        /// </summary>
        public static string PartnerProgram {
            get {
                return ResourceManager.GetString("PartnerProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polityka prywatności.
        /// </summary>
        public static string PolicyPrivate {
            get {
                return ResourceManager.GetString("PolicyPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regulamin.
        /// </summary>
        public static string PolicyWeb {
            get {
                return ResourceManager.GetString("PolicyWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustawienia.
        /// </summary>
        public static string ProfileEdit {
            get {
                return ResourceManager.GetString("ProfileEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mój profil.
        /// </summary>
        public static string ProfileSection {
            get {
                return ResourceManager.GetString("ProfileSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pytania użytkowników.
        /// </summary>
        public static string PublicQuestionList {
            get {
                return ResourceManager.GetString("PublicQuestionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katalog pytań.
        /// </summary>
        public static string QuestionsCatalog {
            get {
                return ResourceManager.GetString("QuestionsCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pytania.
        /// </summary>
        public static string QuestionsModeration {
            get {
                return ResourceManager.GetString("QuestionsModeration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pytania do oczyszczenia.
        /// </summary>
        public static string QuestionsSanitization {
            get {
                return ResourceManager.GetString("QuestionsSanitization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poleć eksperta.
        /// </summary>
        public static string RecommendExpert {
            get {
                return ResourceManager.GetString("RecommendExpert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyślij.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logowanie.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyloguj się.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejestracja.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przepraszamy, wystąpił błąd..
        /// </summary>
        public static string SorryForError {
            get {
                return ResourceManager.GetString("SorryForError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statystyki.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biuro Obsługi Klienta.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownicy.
        /// </summary>
        public static string UsersModeration {
            get {
                return ResourceManager.GetString("UsersModeration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pytania użytkowników.
        /// </summary>
        public static string UsersThreads {
            get {
                return ResourceManager.GetString("UsersThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witaj {0}!.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
