//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Metadata {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Metadata() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Experts.Resources.App_LocalResources.Metadata", typeof(Metadata).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktywacja konta użytkownika..
        /// </summary>
        public static string Account_Activate_Description {
            get {
                return ResourceManager.GetString("Account_Activate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktywacja konta.
        /// </summary>
        public static string Account_Activate_Title {
            get {
                return ResourceManager.GetString("Account_Activate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zostań ekspertem.
        /// </summary>
        public static string Account_BecomeExpert_Title {
            get {
                return ResourceManager.GetString("Account_BecomeExpert_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zostań partnerem.
        /// </summary>
        public static string Account_BecomePartner_Title {
            get {
                return ResourceManager.GetString("Account_BecomePartner_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprecyzuj kompetencje w kategorii.
        /// </summary>
        public static string Account_ExpertCategoryAttributes_Title {
            get {
                return ResourceManager.GetString("Account_ExpertCategoryAttributes_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zgłoszenie nowego eksperta. .
        /// </summary>
        public static string Account_ExpertSignUp_Description {
            get {
                return ResourceManager.GetString("Account_ExpertSignUp_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zostań ekspertem.
        /// </summary>
        public static string Account_ExpertSignUp_Title {
            get {
                return ResourceManager.GetString("Account_ExpertSignUp_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Account_KeySignIn_Description {
            get {
                return ResourceManager.GetString("Account_KeySignIn_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Account_KeySignIn_Title {
            get {
                return ResourceManager.GetString("Account_KeySignIn_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przypomnienie hasła w portalu..
        /// </summary>
        public static string Account_PasswordForgotten_Description {
            get {
                return ResourceManager.GetString("Account_PasswordForgotten_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przypomnienie hasła.
        /// </summary>
        public static string Account_PasswordForgotten_Title {
            get {
                return ResourceManager.GetString("Account_PasswordForgotten_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponowne wysłanie linku aktywacyjnego..
        /// </summary>
        public static string Account_ResendActivationEmail_Description {
            get {
                return ResourceManager.GetString("Account_ResendActivationEmail_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponownie wysłanie linku aktywacyjnego.
        /// </summary>
        public static string Account_ResendActivationEmail_Title {
            get {
                return ResourceManager.GetString("Account_ResendActivationEmail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustawianie nowego hasła w portalu..
        /// </summary>
        public static string Account_ResetPassword_Description {
            get {
                return ResourceManager.GetString("Account_ResetPassword_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpisz nowe hasło.
        /// </summary>
        public static string Account_ResetPassword_Title {
            get {
                return ResourceManager.GetString("Account_ResetPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logowanie do portalu..
        /// </summary>
        public static string Account_SignIn_Description {
            get {
                return ResourceManager.GetString("Account_SignIn_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logowanie.
        /// </summary>
        public static string Account_SignIn_Title {
            get {
                return ResourceManager.GetString("Account_SignIn_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Account_SignOut_Title {
            get {
                return ResourceManager.GetString("Account_SignOut_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejestracja konta użytkownika..
        /// </summary>
        public static string Account_SignUp_Description {
            get {
                return ResourceManager.GetString("Account_SignUp_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejestracja.
        /// </summary>
        public static string Account_SignUp_Title {
            get {
                return ResourceManager.GetString("Account_SignUp_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista kategorii.
        /// </summary>
        public static string Administration_CategoryList_Title {
            get {
                return ResourceManager.GetString("Administration_CategoryList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowy atrybut kategorii.
        /// </summary>
        public static string Administration_CreateCategoryAttribute_Title {
            get {
                return ResourceManager.GetString("Administration_CreateCategoryAttribute_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowy podatrybut.
        /// </summary>
        public static string Administration_CreateChildCategoryAttribute_Title {
            get {
                return ResourceManager.GetString("Administration_CreateChildCategoryAttribute_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń atrybut.
        /// </summary>
        public static string Administration_DeleteCategoryAttribute_Title {
            get {
                return ResourceManager.GetString("Administration_DeleteCategoryAttribute_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edycja atrybutu.
        /// </summary>
        public static string Administration_EditCategoryAttribute_Title {
            get {
                return ResourceManager.GetString("Administration_EditCategoryAttribute_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log systemowy.
        /// </summary>
        public static string Administration_EventsLog_Title {
            get {
                return ResourceManager.GetString("Administration_EventsLog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista użytkowników.
        /// </summary>
        public static string Administration_UserList_Title {
            get {
                return ResourceManager.GetString("Administration_UserList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Catalog_AddKeyword_Title {
            get {
                return ResourceManager.GetString("Catalog_AddKeyword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Najpopulaniejsi eksperci w portalu..
        /// </summary>
        public static string Catalog_ExpertListSeo_Description {
            get {
                return ResourceManager.GetString("Catalog_ExpertListSeo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyszukiwany ekspert.
        /// </summary>
        public static string Catalog_ExpertListSeo_Title {
            get {
                return ResourceManager.GetString("Catalog_ExpertListSeo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Najpopulaniejsi eksperci w portalu..
        /// </summary>
        public static string Catalog_KeywordListExperts_Description {
            get {
                return ResourceManager.GetString("Catalog_KeywordListExperts_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popularni eksperci.
        /// </summary>
        public static string Catalog_KeywordListExperts_Title {
            get {
                return ResourceManager.GetString("Catalog_KeywordListExperts_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Najczęściej wyszukiwane frazy..
        /// </summary>
        public static string Catalog_KeywordListPhrases_Description {
            get {
                return ResourceManager.GetString("Catalog_KeywordListPhrases_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyszukiwane zwroty.
        /// </summary>
        public static string Catalog_KeywordListPhrases_Title {
            get {
                return ResourceManager.GetString("Catalog_KeywordListPhrases_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Najpopularniejsze temat pytań w portalu..
        /// </summary>
        public static string Catalog_KeywordListQuestions_Description {
            get {
                return ResourceManager.GetString("Catalog_KeywordListQuestions_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popularne tematy pytań.
        /// </summary>
        public static string Catalog_KeywordListQuestions_Title {
            get {
                return ResourceManager.GetString("Catalog_KeywordListQuestions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popularne wyszukiwane zwroty..
        /// </summary>
        public static string Catalog_PhraseDetails_Description {
            get {
                return ResourceManager.GetString("Catalog_PhraseDetails_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyszukiwany zwrot.
        /// </summary>
        public static string Catalog_PhraseDetails_Title {
            get {
                return ResourceManager.GetString("Catalog_PhraseDetails_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderacja słowa kluczowego.
        /// </summary>
        public static string Catalog_ProcessKeyword_Title {
            get {
                return ResourceManager.GetString("Catalog_ProcessKeyword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista tematów bez odpowiedzi..
        /// </summary>
        public static string Catalog_QuestionListSeo_Description {
            get {
                return ResourceManager.GetString("Catalog_QuestionListSeo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista tematów bez odpowiedzi.
        /// </summary>
        public static string Catalog_QuestionListSeo_Title {
            get {
                return ResourceManager.GetString("Catalog_QuestionListSeo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderacja słowa kluczowego.
        /// </summary>
        public static string Catalog_SetKeywordAttributes_Title {
            get {
                return ResourceManager.GetString("Catalog_SetKeywordAttributes_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Catalog_SiteMapXml_Description {
            get {
                return ResourceManager.GetString("Catalog_SiteMapXml_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Catalog_SiteMapXml_Title {
            get {
                return ResourceManager.GetString("Catalog_SiteMapXml_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Catalog_StoreKeyword_Title {
            get {
                return ResourceManager.GetString("Catalog_StoreKeyword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pytania użytkowników.
        /// </summary>
        public static string Chat_ChatsOverview_Title {
            get {
                return ResourceManager.GetString("Chat_ChatsOverview_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Chat_CreateMessage_Description {
            get {
                return ResourceManager.GetString("Chat_CreateMessage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Chat_CreateMessage_Title {
            get {
                return ResourceManager.GetString("Chat_CreateMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biuro Obsługi Klienta.
        /// </summary>
        public static string Chat_Support_Title {
            get {
                return ResourceManager.GetString("Chat_Support_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Error_Error500_Description {
            get {
                return ResourceManager.GetString("Error_Error500_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd aplikacji.
        /// </summary>
        public static string Error_Error500_Title {
            get {
                return ResourceManager.GetString("Error_Error500_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Launch_ExpertSubscribe_Description {
            get {
                return ResourceManager.GetString("Launch_ExpertSubscribe_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to asknuts.com - potwierdzenie.
        /// </summary>
        public static string Launch_ExpertSubscribe_Title {
            get {
                return ResourceManager.GetString("Launch_ExpertSubscribe_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Launch_UserSubscribe_Description {
            get {
                return ResourceManager.GetString("Launch_UserSubscribe_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to asknuts.com - potwierdzenie.
        /// </summary>
        public static string Launch_UserSubscribe_Title {
            get {
                return ResourceManager.GetString("Launch_UserSubscribe_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Launch_Welcome_Description {
            get {
                return ResourceManager.GetString("Launch_Welcome_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to asknuts.com - Witamy!.
        /// </summary>
        public static string Launch_Welcome_Title {
            get {
                return ResourceManager.GetString("Launch_Welcome_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wynik wpłaty środków za odpowiedź..
        /// </summary>
        public static string Payment_PaymentConfirmation_Title {
            get {
                return ResourceManager.GetString("Payment_PaymentConfirmation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Payment_ProcessPayment_Title {
            get {
                return ResourceManager.GetString("Payment_ProcessPayment_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilans płatności.
        /// </summary>
        public static string Profile_Balance_Title {
            get {
                return ResourceManager.GetString("Profile_Balance_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejestracja polecanego eksperta..
        /// </summary>
        public static string Profile_CheckExpertRegistration_Description {
            get {
                return ResourceManager.GetString("Profile_CheckExpertRegistration_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarejestruj się z polecenia.
        /// </summary>
        public static string Profile_CheckExpertRegistration_Title {
            get {
                return ResourceManager.GetString("Profile_CheckExpertRegistration_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Profile_ConfirmEmail_Title {
            get {
                return ResourceManager.GetString("Profile_ConfirmEmail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil użytkownika.
        /// </summary>
        public static string Profile_Edit_Title {
            get {
                return ResourceManager.GetString("Profile_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Profile_EditCategories_Title {
            get {
                return ResourceManager.GetString("Profile_EditCategories_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Profile_EditEmail_Title {
            get {
                return ResourceManager.GetString("Profile_EditEmail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Profile_EditExpertMicroprofile_Title {
            get {
                return ResourceManager.GetString("Profile_EditExpertMicroprofile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Profile_EditExpertPublicName_Title {
            get {
                return ResourceManager.GetString("Profile_EditExpertPublicName_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Profile_EditModeratorPublicName_Title {
            get {
                return ResourceManager.GetString("Profile_EditModeratorPublicName_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Profile_EditPassword_Title {
            get {
                return ResourceManager.GetString("Profile_EditPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Profile_EditPhoneNumber_Title {
            get {
                return ResourceManager.GetString("Profile_EditPhoneNumber_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informację o zweryfikowanym przez nas ekspercie..
        /// </summary>
        public static string Profile_ExpertOverview_Description {
            get {
                return ResourceManager.GetString("Profile_ExpertOverview_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacje o ekspercie.
        /// </summary>
        public static string Profile_ExpertOverview_Title {
            get {
                return ResourceManager.GetString("Profile_ExpertOverview_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statystyki ocen i aktywności eksperta..
        /// </summary>
        public static string Profile_ExpertStatistics_Description {
            get {
                return ResourceManager.GetString("Profile_ExpertStatistics_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statystyki eksperta.
        /// </summary>
        public static string Profile_ExpertStatistics_Title {
            get {
                return ResourceManager.GetString("Profile_ExpertStatistics_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista ocen eksperta.
        /// </summary>
        public static string Profile_FeedbackList_Title {
            get {
                return ResourceManager.GetString("Profile_FeedbackList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moje odpowiedzi.
        /// </summary>
        public static string Profile_MyAnswers_Title {
            get {
                return ResourceManager.GetString("Profile_MyAnswers_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moje pytania.
        /// </summary>
        public static string Profile_MyQuestions_Title {
            get {
                return ResourceManager.GetString("Profile_MyQuestions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Profile_OpinionSingle_Description {
            get {
                return ResourceManager.GetString("Profile_OpinionSingle_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Profile_OpinionSingle_Title {
            get {
                return ResourceManager.GetString("Profile_OpinionSingle_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program partnerski.
        /// </summary>
        public static string Profile_PartnerProgram_Title {
            get {
                return ResourceManager.GetString("Profile_PartnerProgram_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statystyki partnera.
        /// </summary>
        public static string Profile_PartnerStatistics_Title {
            get {
                return ResourceManager.GetString("Profile_PartnerStatistics_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Profile_UploadImage_Title {
            get {
                return ResourceManager.GetString("Profile_UploadImage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Profile_UserOpinion_Title {
            get {
                return ResourceManager.GetString("Profile_UserOpinion_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StaticPages_AdCampaignHome_Description {
            get {
                return ResourceManager.GetString("StaticPages_AdCampaignHome_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StaticPages_AdCampaignHome_Title {
            get {
                return ResourceManager.GetString("StaticPages_AdCampaignHome_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profesjonalni eksperci i odpowiedzi na pytania. Gwarancja satysfakcji. Prawo, podatki, finanse, zdrowie,  nauka, miłość i uczucia..
        /// </summary>
        public static string StaticPages_Home_Description {
            get {
                return ResourceManager.GetString("StaticPages_Home_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadaj pytanie ekspertom!.
        /// </summary>
        public static string StaticPages_Home_Title {
            get {
                return ResourceManager.GetString("StaticPages_Home_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dowiedz się więcej o portalu Asknuts. Baza wiedzy o Asknuts.com.
        /// </summary>
        public static string StaticPages_MeetAsknuts_Description {
            get {
                return ResourceManager.GetString("StaticPages_MeetAsknuts_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poznaj &lt;span&gt;AskNuts!&lt;/span&gt;.
        /// </summary>
        public static string StaticPages_MeetAsknuts_Title {
            get {
                return ResourceManager.GetString("StaticPages_MeetAsknuts_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StaticPages_PageNotFound_Description {
            get {
                return ResourceManager.GetString("StaticPages_PageNotFound_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StaticPages_PageNotFound_Title {
            get {
                return ResourceManager.GetString("StaticPages_PageNotFound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodatkowe usługi.
        /// </summary>
        public static string Thread_AdditionalServiceInformation_Title {
            get {
                return ResourceManager.GetString("Thread_AdditionalServiceInformation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pytania zadane przez użytkowników.
        /// </summary>
        public static string Thread_AvailableQuestionList_Title {
            get {
                return ResourceManager.GetString("Thread_AvailableQuestionList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Thread_CatalogQuestionList_Description {
            get {
                return ResourceManager.GetString("Thread_CatalogQuestionList_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katalog odpowiedzi.
        /// </summary>
        public static string Thread_CatalogQuestionList_Title {
            get {
                return ResourceManager.GetString("Thread_CatalogQuestionList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Thread_CatalogThreadDetails_Description {
            get {
                return ResourceManager.GetString("Thread_CatalogThreadDetails_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Thread_CatalogThreadDetails_Title {
            get {
                return ResourceManager.GetString("Thread_CatalogThreadDetails_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Thread_CategoryAttributes_Description {
            get {
                return ResourceManager.GetString("Thread_CategoryAttributes_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprecyzuj pytanie.
        /// </summary>
        public static string Thread_CategoryAttributes_Title {
            get {
                return ResourceManager.GetString("Thread_CategoryAttributes_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Thread_CreatePost_Title {
            get {
                return ResourceManager.GetString("Thread_CreatePost_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Thread_DeclineAdditionalService_Title {
            get {
                return ResourceManager.GetString("Thread_DeclineAdditionalService_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Thread_DeleteAttachment_Title {
            get {
                return ResourceManager.GetString("Thread_DeleteAttachment_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Thread_DeletePost_Title {
            get {
                return ResourceManager.GetString("Thread_DeletePost_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Thread_DeleteThread_Title {
            get {
                return ResourceManager.GetString("Thread_DeleteThread_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Thread_GetAttachment_Description {
            get {
                return ResourceManager.GetString("Thread_GetAttachment_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Thread_GetAttachment_Title {
            get {
                return ResourceManager.GetString("Thread_GetAttachment_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Thread_GiveUp_Title {
            get {
                return ResourceManager.GetString("Thread_GiveUp_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderacja pytań.
        /// </summary>
        public static string Thread_ModeratorQuestionList_Title {
            get {
                return ResourceManager.GetString("Thread_ModeratorQuestionList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Thread_MultiExpertBox_Description {
            get {
                return ResourceManager.GetString("Thread_MultiExpertBox_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Thread_MultiExpertBox_Title {
            get {
                return ResourceManager.GetString("Thread_MultiExpertBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Thread_OccupyThread_Title {
            get {
                return ResourceManager.GetString("Thread_OccupyThread_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Thread_Options_Description {
            get {
                return ResourceManager.GetString("Thread_Options_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz opcję cenową.
        /// </summary>
        public static string Thread_Options_Title {
            get {
                return ResourceManager.GetString("Thread_Options_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Thread_PriceProposalForm_Title {
            get {
                return ResourceManager.GetString("Thread_PriceProposalForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Thread_ProposeAdditionalService_Title {
            get {
                return ResourceManager.GetString("Thread_ProposeAdditionalService_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Thread_ReleaseReservedQuestion_Title {
            get {
                return ResourceManager.GetString("Thread_ReleaseReservedQuestion_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Thread_ReportIssueForm_Title {
            get {
                return ResourceManager.GetString("Thread_ReportIssueForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pytanie użytkownika.
        /// </summary>
        public static string Thread_Sanitization_Title {
            get {
                return ResourceManager.GetString("Thread_Sanitization_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista wątków do oczyszczenia.
        /// </summary>
        public static string Thread_SanitizationQuestionList_Title {
            get {
                return ResourceManager.GetString("Thread_SanitizationQuestionList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Thread_Save_Description {
            get {
                return ResourceManager.GetString("Thread_Save_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Thread_Save_Title {
            get {
                return ResourceManager.GetString("Thread_Save_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Thread_ShowExpertInfo_Description {
            get {
                return ResourceManager.GetString("Thread_ShowExpertInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacje o ekspercie.
        /// </summary>
        public static string Thread_ShowExpertInfo_Title {
            get {
                return ResourceManager.GetString("Thread_ShowExpertInfo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu konwersacji.
        /// </summary>
        public static string Thread_ShowThreadDetailsMenu_Title {
            get {
                return ResourceManager.GetString("Thread_ShowThreadDetailsMenu_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szczegóły pytania.
        /// </summary>
        public static string Thread_ThreadDetails_Title {
            get {
                return ResourceManager.GetString("Thread_ThreadDetails_Title", resourceCulture);
            }
        }
    }
}
