//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Partner {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Partner() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Experts.Resources.App_LocalResources.Partner", typeof(Partner).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- wybierz kategorię --.
        /// </summary>
        public static string ChooseCategory {
            get {
                return ResourceManager.GetString("ChooseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobierz widget.
        /// </summary>
        public static string DownloadWidget {
            get {
                return ResourceManager.GetString("DownloadWidget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widget na Twoją stronę.
        /// </summary>
        public static string ExpertWidget {
            get {
                return ResourceManager.GetString("ExpertWidget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aby uzyskać dodatkową premię za swoje odpowiedzi zachęć innych do korzystania z portalu. Zaprezentuj widget Asknuts reklamujący Twoją wizytówkę eksperta na swojej stronie www. Użytkownik odwiedzający Twoją wizytówkę może zadać pytanie bezpośrednio Tobie. Jeżeli użytkownik zaakceptuje taką odpowiedź, to oprócz wynagrodzenia otrzymasz dodatkową prowizję za pośrednictwo. Pobierz kod widgetu i umieść go na swojej stronie www..
        /// </summary>
        public static string ExpertWidgetDescription {
            get {
                return ResourceManager.GetString("ExpertWidgetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wizytówka eksperta.
        /// </summary>
        public static string ExpertWidgetHeader {
            get {
                return ResourceManager.GetString("ExpertWidgetHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadaj pytanie najlepszym ekspertom w swoich dziedzinach!.
        /// </summary>
        public static string InvitationText {
            get {
                return ResourceManager.GetString("InvitationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program partnerski.
        /// </summary>
        public static string PartnerProgram {
            get {
                return ResourceManager.GetString("PartnerProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zgłosiłeś już chęć przystąpienia do programu partnerskiego. Gdy tylko Twoja prośba zostanie zaakceptowana, poinformujemy Cię o tym poprzez wiadomość e-mail..
        /// </summary>
        public static string PartnerRequestPendingDescription {
            get {
                return ResourceManager.GetString("PartnerRequestPendingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oczekiwanie na akceptację.
        /// </summary>
        public static string PartnerRequestPendingHeader {
            get {
                return ResourceManager.GetString("PartnerRequestPendingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeżeli posiadasz własną stronę internetową, możesz umieścić na niej widget umożliwiający zadawanie pytań ekspertom AskNuts.com. Wystarczy, że dodasz do swojej strony poniższy kod. Styl widgetu może być dowolnie modyfikowany, aby dostosować go do wyglądu Twojej witryny. Za każde pytanie, które zostało zadane za pośrednictwem tego widgetu, a użytkownik zaakceptował odpowiedź, otrzymasz odpowiednią prowizję. .
        /// </summary>
        public static string PartnerWidgetDescription {
            get {
                return ResourceManager.GetString("PartnerWidgetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pytanie na stronie partnera.
        /// </summary>
        public static string PartnerWidgetHeader {
            get {
                return ResourceManager.GetString("PartnerWidgetHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wpisz treść pytania....
        /// </summary>
        public static string QuestionContentPlaceholder {
            get {
                return ResourceManager.GetString("QuestionContentPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to odpowiedzi.
        /// </summary>
        public static string QuestionsAnswered {
            get {
                return ResourceManager.GetString("QuestionsAnswered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poznaj odpowiedź.
        /// </summary>
        public static string QuestionSubmit {
            get {
                return ResourceManager.GetString("QuestionSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uczestnictwo w programie partnerskim serwisu AskNuts.com pozwala na czerpanie profitów za promowanie serwisu na swojej stronie internetowej. Wystarczy, że umieścisz na niej widget pozwalający na zadawanie pytań naszym ekspertom.&lt;br/&gt;&lt;br/&gt;Już teraz możesz .
        /// </summary>
        public static string SendPartnerRequestDescription {
            get {
                return ResourceManager.GetString("SendPartnerRequestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przystąpienie do programu partnerskiego.
        /// </summary>
        public static string SendPartnerRequestHeader {
            get {
                return ResourceManager.GetString("SendPartnerRequestHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zgłosić chęć przystąpienia do programu partnerskiego..
        /// </summary>
        public static string SendPartnerRequestLink {
            get {
                return ResourceManager.GetString("SendPartnerRequestLink", resourceCulture);
            }
        }
    }
}
