//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Routes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Routes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Experts.Resources.App_LocalResources.Routes", typeof(Routes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aktywuj-konto.
        /// </summary>
        public static string Account_Activate {
            get {
                return ResourceManager.GetString("Account_Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zostan-ekspertem.
        /// </summary>
        public static string Account_BecomeExpert {
            get {
                return ResourceManager.GetString("Account_BecomeExpert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zostan-partnerem.
        /// </summary>
        public static string Account_BecomePartner {
            get {
                return ResourceManager.GetString("Account_BecomePartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to doprecyzuj-kategorie.
        /// </summary>
        public static string Account_ExpertCategoryAttributes {
            get {
                return ResourceManager.GetString("Account_ExpertCategoryAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zarejestruj-sie-jako-ekspert.
        /// </summary>
        public static string Account_ExpertSignUp {
            get {
                return ResourceManager.GetString("Account_ExpertSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zaloguj-sie-przez-email.
        /// </summary>
        public static string Account_KeySignIn {
            get {
                return ResourceManager.GetString("Account_KeySignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to przypomnij-haslo.
        /// </summary>
        public static string Account_PasswordForgotten {
            get {
                return ResourceManager.GetString("Account_PasswordForgotten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wyslij-ponownie-link-aktywacyjny.
        /// </summary>
        public static string Account_ResendActivationEmail {
            get {
                return ResourceManager.GetString("Account_ResendActivationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resetuj-haslo.
        /// </summary>
        public static string Account_ResetPassword {
            get {
                return ResourceManager.GetString("Account_ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zaloguj-sie.
        /// </summary>
        public static string Account_SignIn {
            get {
                return ResourceManager.GetString("Account_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wyloguj-sie.
        /// </summary>
        public static string Account_SignOut {
            get {
                return ResourceManager.GetString("Account_SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zarejestruj-sie.
        /// </summary>
        public static string Account_SignUp {
            get {
                return ResourceManager.GetString("Account_SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lista-kategorii.
        /// </summary>
        public static string Administration_CategoryList {
            get {
                return ResourceManager.GetString("Administration_CategoryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dodaj-atrybut.
        /// </summary>
        public static string Administration_CreateCategoryAttribute {
            get {
                return ResourceManager.GetString("Administration_CreateCategoryAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dodaj-podatrybut.
        /// </summary>
        public static string Administration_CreateChildCategoryAttribute {
            get {
                return ResourceManager.GetString("Administration_CreateChildCategoryAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usun-atrybut.
        /// </summary>
        public static string Administration_DeleteCategoryAttribute {
            get {
                return ResourceManager.GetString("Administration_DeleteCategoryAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edytuj-atrybut.
        /// </summary>
        public static string Administration_EditCategoryAttribute {
            get {
                return ResourceManager.GetString("Administration_EditCategoryAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zdarzenia.
        /// </summary>
        public static string Administration_EventsLog {
            get {
                return ResourceManager.GetString("Administration_EventsLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zarzadzaj-uzytkownikami.
        /// </summary>
        public static string Administration_UserList {
            get {
                return ResourceManager.GetString("Administration_UserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dodaj-slowo-kluczowe.
        /// </summary>
        public static string Catalog_AddKeyword {
            get {
                return ResourceManager.GetString("Catalog_AddKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eksperci.
        /// </summary>
        public static string Catalog_ExpertListSeo {
            get {
                return ResourceManager.GetString("Catalog_ExpertListSeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to popularni-eksperci.
        /// </summary>
        public static string Catalog_KeywordListExperts {
            get {
                return ResourceManager.GetString("Catalog_KeywordListExperts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wyszukiwane-zwroty.
        /// </summary>
        public static string Catalog_KeywordListPhrases {
            get {
                return ResourceManager.GetString("Catalog_KeywordListPhrases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to popularne-tematy-pytan.
        /// </summary>
        public static string Catalog_KeywordListQuestions {
            get {
                return ResourceManager.GetString("Catalog_KeywordListQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to slowo-kluczowe.
        /// </summary>
        public static string Catalog_PhraseDetails {
            get {
                return ResourceManager.GetString("Catalog_PhraseDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moderuj-slowo-kluczowe.
        /// </summary>
        public static string Catalog_ProcessKeyword {
            get {
                return ResourceManager.GetString("Catalog_ProcessKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lista-pytan.
        /// </summary>
        public static string Catalog_QuestionListSeo {
            get {
                return ResourceManager.GetString("Catalog_QuestionListSeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sprecyzuj-slowo-kluczowe.
        /// </summary>
        public static string Catalog_SetKeywordAttributes {
            get {
                return ResourceManager.GetString("Catalog_SetKeywordAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sitemap.xml.
        /// </summary>
        public static string Catalog_SiteMapXml {
            get {
                return ResourceManager.GetString("Catalog_SiteMapXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zapisz-slowo-kluczowe.
        /// </summary>
        public static string Catalog_StoreKeyword {
            get {
                return ResourceManager.GetString("Catalog_StoreKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wiadomosci-klientow.
        /// </summary>
        public static string Chat_ChatsOverview {
            get {
                return ResourceManager.GetString("Chat_ChatsOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wyslij-wiadomosc.
        /// </summary>
        public static string Chat_CreateMessage {
            get {
                return ResourceManager.GetString("Chat_CreateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to panel-obslugi-klienta.
        /// </summary>
        public static string Chat_Support {
            get {
                return ResourceManager.GetString("Chat_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blad-aplikacji.
        /// </summary>
        public static string Error_Error500 {
            get {
                return ResourceManager.GetString("Error_Error500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zglos-eksperta.
        /// </summary>
        public static string Launch_ExpertSubscribe {
            get {
                return ResourceManager.GetString("Launch_ExpertSubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zglos-uzytkownika.
        /// </summary>
        public static string Launch_UserSubscribe {
            get {
                return ResourceManager.GetString("Launch_UserSubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to witamy.
        /// </summary>
        public static string Launch_Welcome {
            get {
                return ResourceManager.GetString("Launch_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to potwierdzenie-platnosci.
        /// </summary>
        public static string Payment_PaymentConfirmation {
            get {
                return ResourceManager.GetString("Payment_PaymentConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to finalizuj-platnosc.
        /// </summary>
        public static string Payment_ProcessPayment {
            get {
                return ResourceManager.GetString("Payment_ProcessPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bilans.
        /// </summary>
        public static string Profile_Balance {
            get {
                return ResourceManager.GetString("Profile_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zarejestruj-sie-z-polecenia.
        /// </summary>
        public static string Profile_CheckExpertRegistration {
            get {
                return ResourceManager.GetString("Profile_CheckExpertRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to potwierdz-email.
        /// </summary>
        public static string Profile_ConfirmEmail {
            get {
                return ResourceManager.GetString("Profile_ConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edytuj-profil.
        /// </summary>
        public static string Profile_Edit {
            get {
                return ResourceManager.GetString("Profile_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edytuj-kategorie.
        /// </summary>
        public static string Profile_EditCategories {
            get {
                return ResourceManager.GetString("Profile_EditCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zmien-email.
        /// </summary>
        public static string Profile_EditEmail {
            get {
                return ResourceManager.GetString("Profile_EditEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edytuj-mikroprofil.
        /// </summary>
        public static string Profile_EditExpertMicroprofile {
            get {
                return ResourceManager.GetString("Profile_EditExpertMicroprofile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zmien-publiczna-nazwe-eksperta.
        /// </summary>
        public static string Profile_EditExpertPublicName {
            get {
                return ResourceManager.GetString("Profile_EditExpertPublicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zmien-publiczna-nazwe-moderatora.
        /// </summary>
        public static string Profile_EditModeratorPublicName {
            get {
                return ResourceManager.GetString("Profile_EditModeratorPublicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zmien-haslo.
        /// </summary>
        public static string Profile_EditPassword {
            get {
                return ResourceManager.GetString("Profile_EditPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zmien-numer-telefonu.
        /// </summary>
        public static string Profile_EditPhoneNumber {
            get {
                return ResourceManager.GetString("Profile_EditPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wizytowka-eksperta.
        /// </summary>
        public static string Profile_ExpertOverview {
            get {
                return ResourceManager.GetString("Profile_ExpertOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wykresy-eksperta.
        /// </summary>
        public static string Profile_ExpertStatistics {
            get {
                return ResourceManager.GetString("Profile_ExpertStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lista-opinii.
        /// </summary>
        public static string Profile_FeedbackList {
            get {
                return ResourceManager.GetString("Profile_FeedbackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moje-odpowiedzi.
        /// </summary>
        public static string Profile_MyAnswers {
            get {
                return ResourceManager.GetString("Profile_MyAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moje-pytania.
        /// </summary>
        public static string Profile_MyQuestions {
            get {
                return ResourceManager.GetString("Profile_MyQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to opinia.
        /// </summary>
        public static string Profile_OpinionSingle {
            get {
                return ResourceManager.GetString("Profile_OpinionSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to program-partnerski.
        /// </summary>
        public static string Profile_PartnerProgram {
            get {
                return ResourceManager.GetString("Profile_PartnerProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to statystyki-partnera.
        /// </summary>
        public static string Profile_PartnerStatistics {
            get {
                return ResourceManager.GetString("Profile_PartnerStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wrzuc-zdjecie.
        /// </summary>
        public static string Profile_UploadImage {
            get {
                return ResourceManager.GetString("Profile_UploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ocen-serwis.
        /// </summary>
        public static string Profile_UserOpinion {
            get {
                return ResourceManager.GetString("Profile_UserOpinion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zadaj-pytanie.
        /// </summary>
        public static string StaticPages_AdCampaignHome {
            get {
                return ResourceManager.GetString("StaticPages_AdCampaignHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StaticPages_Home {
            get {
                return ResourceManager.GetString("StaticPages_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to poznaj-asknuts.
        /// </summary>
        public static string StaticPages_MeetAsknuts {
            get {
                return ResourceManager.GetString("StaticPages_MeetAsknuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blad-404.
        /// </summary>
        public static string StaticPages_PageNotFound {
            get {
                return ResourceManager.GetString("StaticPages_PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dodatkowe-uslugi.
        /// </summary>
        public static string Thread_AdditionalServiceInformation {
            get {
                return ResourceManager.GetString("Thread_AdditionalServiceInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pytania-uzytkownikow.
        /// </summary>
        public static string Thread_AvailableQuestionList {
            get {
                return ResourceManager.GetString("Thread_AvailableQuestionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to katalog-pytan.
        /// </summary>
        public static string Thread_CatalogQuestionList {
            get {
                return ResourceManager.GetString("Thread_CatalogQuestionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pytanie.
        /// </summary>
        public static string Thread_CatalogThreadDetails {
            get {
                return ResourceManager.GetString("Thread_CatalogThreadDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sprecyzuj-pytanie.
        /// </summary>
        public static string Thread_CategoryAttributes {
            get {
                return ResourceManager.GetString("Thread_CategoryAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to odpowiedz.
        /// </summary>
        public static string Thread_CreatePost {
            get {
                return ResourceManager.GetString("Thread_CreatePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to odrzucenie-dodatkowej-uslugi.
        /// </summary>
        public static string Thread_DeclineAdditionalService {
            get {
                return ResourceManager.GetString("Thread_DeclineAdditionalService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usun-zalacznik.
        /// </summary>
        public static string Thread_DeleteAttachment {
            get {
                return ResourceManager.GetString("Thread_DeleteAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usun-wiadomosc.
        /// </summary>
        public static string Thread_DeletePost {
            get {
                return ResourceManager.GetString("Thread_DeletePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usun-watek.
        /// </summary>
        public static string Thread_DeleteThread {
            get {
                return ResourceManager.GetString("Thread_DeleteThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zalacznik.
        /// </summary>
        public static string Thread_GetAttachment {
            get {
                return ResourceManager.GetString("Thread_GetAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zrezygnuj-z-pytania.
        /// </summary>
        public static string Thread_GiveUp {
            get {
                return ResourceManager.GetString("Thread_GiveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moderacja-pytan.
        /// </summary>
        public static string Thread_ModeratorQuestionList {
            get {
                return ResourceManager.GetString("Thread_ModeratorQuestionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eksperci-box.
        /// </summary>
        public static string Thread_MultiExpertBox {
            get {
                return ResourceManager.GetString("Thread_MultiExpertBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zarezerwuj-pytanie.
        /// </summary>
        public static string Thread_OccupyThread {
            get {
                return ResourceManager.GetString("Thread_OccupyThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parametry-pytania.
        /// </summary>
        public static string Thread_Options {
            get {
                return ResourceManager.GetString("Thread_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to formularz-propozycji-ceny.
        /// </summary>
        public static string Thread_PriceProposalForm {
            get {
                return ResourceManager.GetString("Thread_PriceProposalForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zaproponuj-dodatkowa-usluge.
        /// </summary>
        public static string Thread_ProposeAdditionalService {
            get {
                return ResourceManager.GetString("Thread_ProposeAdditionalService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zrezygnuj-z-eksperta.
        /// </summary>
        public static string Thread_ReleaseReservedQuestion {
            get {
                return ResourceManager.GetString("Thread_ReleaseReservedQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to formularz-zglaszania-problemu.
        /// </summary>
        public static string Thread_ReportIssueForm {
            get {
                return ResourceManager.GetString("Thread_ReportIssueForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oczyszczanie-watku.
        /// </summary>
        public static string Thread_Sanitization {
            get {
                return ResourceManager.GetString("Thread_Sanitization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to czyszczenie-pytan.
        /// </summary>
        public static string Thread_SanitizationQuestionList {
            get {
                return ResourceManager.GetString("Thread_SanitizationQuestionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to poznaj-odpowiedz.
        /// </summary>
        public static string Thread_Save {
            get {
                return ResourceManager.GetString("Thread_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to informacje-o-ekspercie.
        /// </summary>
        public static string Thread_ShowExpertInfo {
            get {
                return ResourceManager.GetString("Thread_ShowExpertInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to menu-pytania.
        /// </summary>
        public static string Thread_ShowThreadDetailsMenu {
            get {
                return ResourceManager.GetString("Thread_ShowThreadDetailsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to szczegoly-pytania.
        /// </summary>
        public static string Thread_ThreadDetails {
            get {
                return ResourceManager.GetString("Thread_ThreadDetails", resourceCulture);
            }
        }
    }
}
