//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StaticPages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StaticPages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Experts.Resources.App_LocalResources.StaticPages", typeof(StaticPages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dla-ekspertow.
        /// </summary>
        public static string ExpertFaq {
            get {
                return ResourceManager.GetString("ExpertFaq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to najczesciej-zadawane-pytania.
        /// </summary>
        public static string Faq {
            get {
                return ResourceManager.GetString("Faq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nasi eksperci.
        /// </summary>
        public static string HomeOurExperts {
            get {
                return ResourceManager.GetString("HomeOurExperts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        ///            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
        ///            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
        ///            consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
        ///            cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
        ///            proident, sunt in culpa qui officia deserunt mollit anim id est laboru [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HomeSystemDescription {
            get {
                return ResourceManager.GetString("HomeSystemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asknuts.
        /// </summary>
        public static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opinie.
        /// </summary>
        public static string HomeUserOpinions {
            get {
                return ResourceManager.GetString("HomeUserOpinions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strona nie została odnaleziona.
        /// </summary>
        public static string PageDoesNotExist {
            get {
                return ResourceManager.GetString("PageDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przepraszamy, podana strona nie istnieje.
        /// </summary>
        public static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadaj pytanie ekspertom.
        /// </summary>
        public static string PageNotFound_AskExpertQuestion {
            get {
                return ResourceManager.GetString("PageNotFound_AskExpertQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poznaj AskNuts.
        /// </summary>
        public static string PageNotFound_AskNutsFAQ {
            get {
                return ResourceManager.GetString("PageNotFound_AskNutsFAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wróć na stronę główną.
        /// </summary>
        public static string PageNotFound_GoBackToHome {
            get {
                return ResourceManager.GetString("PageNotFound_GoBackToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upewnij się czy podany adres jest poprawny i spróbuj ponownie, lub:.
        /// </summary>
        public static string PageNotFoundInstructions {
            get {
                return ResourceManager.GetString("PageNotFoundInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to polityka-prywatnosci.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to regulamin.
        /// </summary>
        public static string Terms {
            get {
                return ResourceManager.GetString("Terms", resourceCulture);
            }
        }
    }
}
