// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Experts.Web.Controllers
{
    public partial class CatalogController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public CatalogController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected CatalogController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult ChildCategoryAttributes()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ChildCategoryAttributes);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult IsKeywordUnique()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.IsKeywordUnique);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult AddKeyword()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddKeyword);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult SetKeywordAttributes()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SetKeywordAttributes);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult StoreKeyword()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.StoreKeyword);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult BanKeyword()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.BanKeyword);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult SetKeywordAsUndefined()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SetKeywordAsUndefined);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult PhraseDetails()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PhraseDetails);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult ExpertListSeo()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExpertListSeo);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult QuestionListSeo()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.QuestionListSeo);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public CatalogController Actions { get { return MVC.Catalog; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Catalog";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Catalog";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string ChildCategoryAttributes = "ChildCategoryAttributes";
            public readonly string IsKeywordUnique = "IsKeywordUnique";
            public readonly string AddKeyword = "AddKeyword";
            public readonly string ProcessKeyword = "ProcessKeyword";
            public readonly string SetKeywordAttributes = "SetKeywordAttributes";
            public readonly string StoreKeyword = "StoreKeyword";
            public readonly string BanKeyword = "BanKeyword";
            public readonly string SetKeywordAsUndefined = "SetKeywordAsUndefined";
            public readonly string PhraseDetails = "PhraseDetails";
            public readonly string ExpertListSeo = "ExpertListSeo";
            public readonly string QuestionListSeo = "QuestionListSeo";
            public readonly string KeywordListExperts = "KeywordListExperts";
            public readonly string KeywordListPhrases = "KeywordListPhrases";
            public readonly string KeywordListQuestions = "KeywordListQuestions";
            public readonly string SiteMapXml = "SiteMapXml";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string ChildCategoryAttributes = "ChildCategoryAttributes";
            public const string IsKeywordUnique = "IsKeywordUnique";
            public const string AddKeyword = "AddKeyword";
            public const string ProcessKeyword = "ProcessKeyword";
            public const string SetKeywordAttributes = "SetKeywordAttributes";
            public const string StoreKeyword = "StoreKeyword";
            public const string BanKeyword = "BanKeyword";
            public const string SetKeywordAsUndefined = "SetKeywordAsUndefined";
            public const string PhraseDetails = "PhraseDetails";
            public const string ExpertListSeo = "ExpertListSeo";
            public const string QuestionListSeo = "QuestionListSeo";
            public const string KeywordListExperts = "KeywordListExperts";
            public const string KeywordListPhrases = "KeywordListPhrases";
            public const string KeywordListQuestions = "KeywordListQuestions";
            public const string SiteMapXml = "SiteMapXml";
        }


        static readonly ActionParamsClass_ChildCategoryAttributes s_params_ChildCategoryAttributes = new ActionParamsClass_ChildCategoryAttributes();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ChildCategoryAttributes ChildCategoryAttributesParams { get { return s_params_ChildCategoryAttributes; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ChildCategoryAttributes
        {
            public readonly string attributeValues = "AttributeValues";
            public readonly string attributeId = "attributeId";
        }
        static readonly ActionParamsClass_IsKeywordUnique s_params_IsKeywordUnique = new ActionParamsClass_IsKeywordUnique();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_IsKeywordUnique IsKeywordUniqueParams { get { return s_params_IsKeywordUnique; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_IsKeywordUnique
        {
            public readonly string keywordPhrase = "keywordPhrase";
        }
        static readonly ActionParamsClass_AddKeyword s_params_AddKeyword = new ActionParamsClass_AddKeyword();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddKeyword AddKeywordParams { get { return s_params_AddKeyword; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddKeyword
        {
            public readonly string keywordPhrase = "keywordPhrase";
        }
        static readonly ActionParamsClass_ProcessKeyword s_params_ProcessKeyword = new ActionParamsClass_ProcessKeyword();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ProcessKeyword ProcessKeywordParams { get { return s_params_ProcessKeyword; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ProcessKeyword
        {
            public readonly string form = "form";
        }
        static readonly ActionParamsClass_SetKeywordAttributes s_params_SetKeywordAttributes = new ActionParamsClass_SetKeywordAttributes();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SetKeywordAttributes SetKeywordAttributesParams { get { return s_params_SetKeywordAttributes; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SetKeywordAttributes
        {
            public readonly string form = "KeywordProcessForm";
        }
        static readonly ActionParamsClass_StoreKeyword s_params_StoreKeyword = new ActionParamsClass_StoreKeyword();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_StoreKeyword StoreKeywordParams { get { return s_params_StoreKeyword; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_StoreKeyword
        {
            public readonly string form = "KeywordProcessForm";
        }
        static readonly ActionParamsClass_BanKeyword s_params_BanKeyword = new ActionParamsClass_BanKeyword();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_BanKeyword BanKeywordParams { get { return s_params_BanKeyword; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_BanKeyword
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_SetKeywordAsUndefined s_params_SetKeywordAsUndefined = new ActionParamsClass_SetKeywordAsUndefined();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SetKeywordAsUndefined SetKeywordAsUndefinedParams { get { return s_params_SetKeywordAsUndefined; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SetKeywordAsUndefined
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_PhraseDetails s_params_PhraseDetails = new ActionParamsClass_PhraseDetails();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PhraseDetails PhraseDetailsParams { get { return s_params_PhraseDetails; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PhraseDetails
        {
            public readonly string keywordId = "keywordId";
            public readonly string title = "title";
        }
        static readonly ActionParamsClass_ExpertListSeo s_params_ExpertListSeo = new ActionParamsClass_ExpertListSeo();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ExpertListSeo ExpertListSeoParams { get { return s_params_ExpertListSeo; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ExpertListSeo
        {
            public readonly string keywordId = "keywordId";
            public readonly string title = "title";
        }
        static readonly ActionParamsClass_QuestionListSeo s_params_QuestionListSeo = new ActionParamsClass_QuestionListSeo();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_QuestionListSeo QuestionListSeoParams { get { return s_params_QuestionListSeo; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_QuestionListSeo
        {
            public readonly string keywordId = "keywordId";
            public readonly string title = "title";
        }
        static readonly ActionParamsClass_KeywordListExperts s_params_KeywordListExperts = new ActionParamsClass_KeywordListExperts();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_KeywordListExperts KeywordListExpertsParams { get { return s_params_KeywordListExperts; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_KeywordListExperts
        {
            public readonly string page = "page";
        }
        static readonly ActionParamsClass_KeywordListPhrases s_params_KeywordListPhrases = new ActionParamsClass_KeywordListPhrases();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_KeywordListPhrases KeywordListPhrasesParams { get { return s_params_KeywordListPhrases; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_KeywordListPhrases
        {
            public readonly string page = "page";
        }
        static readonly ActionParamsClass_KeywordListQuestions s_params_KeywordListQuestions = new ActionParamsClass_KeywordListQuestions();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_KeywordListQuestions KeywordListQuestionsParams { get { return s_params_KeywordListQuestions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_KeywordListQuestions
        {
            public readonly string page = "page";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _AddKeywordWindow = "_AddKeywordWindow";
                public readonly string _KeywordCategoryAttributes = "_KeywordCategoryAttributes";
                public readonly string ExpertListSeo = "ExpertListSeo";
                public readonly string KeywordListExperts = "KeywordListExperts";
                public readonly string KeywordListPhrases = "KeywordListPhrases";
                public readonly string KeywordListQuestions = "KeywordListQuestions";
                public readonly string NoNewKeyword = "NoNewKeyword";
                public readonly string PhraseDetails = "PhraseDetails";
                public readonly string ProcessKeyword = "ProcessKeyword";
                public readonly string QuestionListSeo = "QuestionListSeo";
                public readonly string SetKeywordAttributes = "SetKeywordAttributes";
            }
            public readonly string _AddKeywordWindow = "~/Views/Catalog/_AddKeywordWindow.cshtml";
            public readonly string _KeywordCategoryAttributes = "~/Views/Catalog/_KeywordCategoryAttributes.cshtml";
            public readonly string ExpertListSeo = "~/Views/Catalog/ExpertListSeo.cshtml";
            public readonly string KeywordListExperts = "~/Views/Catalog/KeywordListExperts.cshtml";
            public readonly string KeywordListPhrases = "~/Views/Catalog/KeywordListPhrases.cshtml";
            public readonly string KeywordListQuestions = "~/Views/Catalog/KeywordListQuestions.cshtml";
            public readonly string NoNewKeyword = "~/Views/Catalog/NoNewKeyword.cshtml";
            public readonly string PhraseDetails = "~/Views/Catalog/PhraseDetails.cshtml";
            public readonly string ProcessKeyword = "~/Views/Catalog/ProcessKeyword.cshtml";
            public readonly string QuestionListSeo = "~/Views/Catalog/QuestionListSeo.cshtml";
            public readonly string SetKeywordAttributes = "~/Views/Catalog/SetKeywordAttributes.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_CatalogController : Experts.Web.Controllers.CatalogController
    {
        public T4MVC_CatalogController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult ChildCategoryAttributes(Experts.Web.Models.Shared.AttributeValueModel[] attributeValues, int attributeId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ChildCategoryAttributes);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "AttributeValues", attributeValues);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "attributeId", attributeId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult IsKeywordUnique(string keywordPhrase)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.IsKeywordUnique);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "keywordPhrase", keywordPhrase);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult AddKeyword(string keywordPhrase)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddKeyword);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "keywordPhrase", keywordPhrase);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ProcessKeyword(Experts.Web.Models.Catalog.KeywordProcessForm form)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ProcessKeyword);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "form", form);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult SetKeywordAttributes(Experts.Web.Models.Catalog.KeywordProcessForm form)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SetKeywordAttributes);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "KeywordProcessForm", form);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult StoreKeyword(Experts.Web.Models.Catalog.KeywordProcessForm form)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.StoreKeyword);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "KeywordProcessForm", form);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult BanKeyword(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.BanKeyword);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult SetKeywordAsUndefined(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SetKeywordAsUndefined);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult PhraseDetails(int keywordId, string title)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PhraseDetails);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "keywordId", keywordId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "title", title);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ExpertListSeo(int keywordId, string title)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExpertListSeo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "keywordId", keywordId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "title", title);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult QuestionListSeo(int keywordId, string title)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.QuestionListSeo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "keywordId", keywordId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "title", title);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult KeywordListExperts(int? page)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.KeywordListExperts);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult KeywordListPhrases(int? page)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.KeywordListPhrases);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult KeywordListQuestions(int? page)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.KeywordListQuestions);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult SiteMapXml()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SiteMapXml);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
