// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Experts.Web.Controllers
{
    public partial class LaunchController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public LaunchController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected LaunchController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult UserSubscribe()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UserSubscribe);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult ExpertSubscribe()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExpertSubscribe);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public LaunchController Actions { get { return MVC.Launch; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Launch";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Launch";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Welcome = "Welcome";
            public readonly string UserSubscribe = "UserSubscribe";
            public readonly string ExpertSubscribe = "ExpertSubscribe";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Welcome = "Welcome";
            public const string UserSubscribe = "UserSubscribe";
            public const string ExpertSubscribe = "ExpertSubscribe";
        }


        static readonly ActionParamsClass_UserSubscribe s_params_UserSubscribe = new ActionParamsClass_UserSubscribe();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UserSubscribe UserSubscribeParams { get { return s_params_UserSubscribe; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UserSubscribe
        {
            public readonly string email = "email";
        }
        static readonly ActionParamsClass_ExpertSubscribe s_params_ExpertSubscribe = new ActionParamsClass_ExpertSubscribe();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ExpertSubscribe ExpertSubscribeParams { get { return s_params_ExpertSubscribe; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ExpertSubscribe
        {
            public readonly string contact = "contact";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _Layout = "_Layout";
                public readonly string _ViewStart = "_ViewStart";
                public readonly string ExpertSubscribe = "ExpertSubscribe";
                public readonly string UserSubscribe = "UserSubscribe";
                public readonly string Welcome = "Welcome";
            }
            public readonly string _Layout = "~/Views/Launch/_Layout.cshtml";
            public readonly string _ViewStart = "~/Views/Launch/_ViewStart.cshtml";
            public readonly string ExpertSubscribe = "~/Views/Launch/ExpertSubscribe.cshtml";
            public readonly string UserSubscribe = "~/Views/Launch/UserSubscribe.cshtml";
            public readonly string Welcome = "~/Views/Launch/Welcome.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_LaunchController : Experts.Web.Controllers.LaunchController
    {
        public T4MVC_LaunchController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Welcome()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Welcome);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult UserSubscribe(string email)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UserSubscribe);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "email", email);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ExpertSubscribe(string contact)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExpertSubscribe);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "contact", contact);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
