// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Experts.Web.Controllers
{
    public partial class LogController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public LogController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected LogController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Debug()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Debug);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Info()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Info);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Warn()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Warn);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Error()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Error);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Fatal()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Fatal);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public LogController Actions { get { return MVC.Log; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Log";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Log";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Debug = "Debug";
            public readonly string Info = "Info";
            public readonly string Warn = "Warn";
            public readonly string Error = "Error";
            public readonly string Fatal = "Fatal";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Debug = "Debug";
            public const string Info = "Info";
            public const string Warn = "Warn";
            public const string Error = "Error";
            public const string Fatal = "Fatal";
        }


        static readonly ActionParamsClass_Debug s_params_Debug = new ActionParamsClass_Debug();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Debug DebugParams { get { return s_params_Debug; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Debug
        {
            public readonly string webLogEntity = "webLogEntity";
        }
        static readonly ActionParamsClass_Info s_params_Info = new ActionParamsClass_Info();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Info InfoParams { get { return s_params_Info; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Info
        {
            public readonly string webLogEntity = "webLogEntity";
        }
        static readonly ActionParamsClass_Warn s_params_Warn = new ActionParamsClass_Warn();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Warn WarnParams { get { return s_params_Warn; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Warn
        {
            public readonly string webLogEntity = "webLogEntity";
        }
        static readonly ActionParamsClass_Error s_params_Error = new ActionParamsClass_Error();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Error ErrorParams { get { return s_params_Error; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Error
        {
            public readonly string webLogEntity = "webLogEntity";
        }
        static readonly ActionParamsClass_Fatal s_params_Fatal = new ActionParamsClass_Fatal();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Fatal FatalParams { get { return s_params_Fatal; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Fatal
        {
            public readonly string webLogEntity = "webLogEntity";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_LogController : Experts.Web.Controllers.LogController
    {
        public T4MVC_LogController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Debug(Experts.Web.Logging.WebLogEntity webLogEntity)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Debug);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "webLogEntity", webLogEntity);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Info(Experts.Web.Logging.WebLogEntity webLogEntity)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Info);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "webLogEntity", webLogEntity);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Warn(Experts.Web.Logging.WebLogEntity webLogEntity)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Warn);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "webLogEntity", webLogEntity);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Error(Experts.Web.Logging.WebLogEntity webLogEntity)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Error);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "webLogEntity", webLogEntity);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Fatal(Experts.Web.Logging.WebLogEntity webLogEntity)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Fatal);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "webLogEntity", webLogEntity);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
