// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC
{
    public class SharedController
    {

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _GoogleAnalytics = "_GoogleAnalytics";
                public readonly string _Layout = "_Layout";
                public readonly string _Pager = "_Pager";
                public readonly string _TopMenu = "_TopMenu";
                public readonly string _ValidationSummary = "_ValidationSummary";
                public readonly string ActionLinkWithConfirmation = "ActionLinkWithConfirmation";
                public readonly string Error404 = "Error404";
                public readonly string Error500 = "Error500";
                public readonly string FlashMessage = "FlashMessage";
                public readonly string Opinions = "Opinions";
            }
            public readonly string _GoogleAnalytics = "~/Views/Shared/_GoogleAnalytics.cshtml";
            public readonly string _Layout = "~/Views/Shared/_Layout.cshtml";
            public readonly string _Pager = "~/Views/Shared/_Pager.cshtml";
            public readonly string _TopMenu = "~/Views/Shared/_TopMenu.cshtml";
            public readonly string _ValidationSummary = "~/Views/Shared/_ValidationSummary.cshtml";
            public readonly string ActionLinkWithConfirmation = "~/Views/Shared/ActionLinkWithConfirmation.cshtml";
            public readonly string Error404 = "~/Views/Shared/Error404.cshtml";
            public readonly string Error500 = "~/Views/Shared/Error500.cshtml";
            public readonly string FlashMessage = "~/Views/Shared/FlashMessage.cshtml";
            public readonly string Opinions = "~/Views/Shared/Opinions.cshtml";
            static readonly _DisplayTemplatesClass s_DisplayTemplates = new _DisplayTemplatesClass();
            public _DisplayTemplatesClass DisplayTemplates { get { return s_DisplayTemplates; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _DisplayTemplatesClass
            {
                public readonly string MenuHelperModel = "MenuHelperModel";
                public readonly string MenuHelperModel_cshtml = "MenuHelperModel";
                public readonly string SiteMapHelperModel = "SiteMapHelperModel";
                public readonly string SiteMapHelperModel_cshtml = "SiteMapHelperModel";
                public readonly string SiteMapNodeModel = "SiteMapNodeModel";
                public readonly string SiteMapNodeModel_cshtml = "SiteMapNodeModel";
                public readonly string SiteMapNodeModelList = "SiteMapNodeModelList";
                public readonly string SiteMapNodeModelList_cshtml = "SiteMapNodeModelList";
                public readonly string SiteMapPathHelperModel = "SiteMapPathHelperModel";
                public readonly string SiteMapPathHelperModel_cshtml = "SiteMapPathHelperModel";
                public readonly string SiteMapTitleHelperModel = "SiteMapTitleHelperModel";
                public readonly string SiteMapTitleHelperModel_cshtml = "SiteMapTitleHelperModel";
            }
            static readonly _EditorTemplatesClass s_EditorTemplates = new _EditorTemplatesClass();
            public _EditorTemplatesClass EditorTemplates { get { return s_EditorTemplates; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _EditorTemplatesClass
            {
                public readonly string Categories = "Categories";
                public readonly string CategoryAttributeForm = "CategoryAttributeForm";
                public readonly string Decimal = "Decimal";
                public readonly string ExpertProfileFormModel = "ExpertProfileFormModel";
                public readonly string Int32 = "Int32";
                public readonly string Mails = "Mails";
                public readonly string MultilineText = "MultilineText";
                public readonly string Object = "Object";
                public readonly string Password = "Password";
                public readonly string PasswordForm = "PasswordForm";
                public readonly string ProfileForm = "ProfileForm";
                public readonly string SimplePasswordForm = "SimplePasswordForm";
                public readonly string String = "String";
            }
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591
