// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.296
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Experts.Specs.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Dostępność stron statycznych")]
    public partial class DostepnoscStronStatycznychFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "StaticPages.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pl-PL"), "Dostępność stron statycznych", "Aby sprawdzić czy aplikacja poprawnie się uruchamia\r\nsprawdzamy zawartość strony " +
                    "głównej", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Sprawdzamy czy strona główna jest dostępna")]
        public virtual void SprawdzamyCzyStronaGlownaJestDostepna()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Sprawdzamy czy strona główna jest dostępna", ((string[])(null)));
#line 5
this.ScenarioSetup(scenarioInfo);
#line 6
 testRunner.When("przejdę do /", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Jeśli ");
#line 7
 testRunner.Then("zobaczę tekst Zadaj pytanie ekspertowi!", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Wtedy ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Dostępność strony Poznaj Asknuts")]
        public virtual void DostepnoscStronyPoznajAsknuts()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Dostępność strony Poznaj Asknuts", ((string[])(null)));
#line 9
this.ScenarioSetup(scenarioInfo);
#line 10
 testRunner.When("przejdę do /", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Jeśli ");
#line 11
 testRunner.And("kliknę przycisk Poznaj AskNuts!", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Oraz ");
#line 12
 testRunner.Then("zobaczę tekst Poznaj AskNuts!", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Wtedy ");
#line 13
 testRunner.And("zobaczę tekst Gwarancja anonimowości!", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Oraz ");
#line 14
 testRunner.And("zobaczę tekst Przede wszystkim zaufani eksperci!", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Oraz ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Dostępność strony Poznaj Asknuts Regulamin")]
        public virtual void DostepnoscStronyPoznajAsknutsRegulamin()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Dostępność strony Poznaj Asknuts Regulamin", ((string[])(null)));
#line 16
this.ScenarioSetup(scenarioInfo);
#line 17
 testRunner.When("przejdę do /", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Jeśli ");
#line 18
 testRunner.And("kliknę przycisk Regulamin", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Oraz ");
#line 19
 testRunner.Then("zobaczę tekst Poznaj AskNuts!", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Wtedy ");
#line 20
 testRunner.And("zobaczę tekst Gwarancja anonimowości!", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Oraz ");
#line 21
 testRunner.And("zobaczę tekst Przede wszystkim zaufani eksperci!", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Oraz ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Dostępność strony Poznaj Asknuts Polityka Prywatności")]
        public virtual void DostepnoscStronyPoznajAsknutsPolitykaPrywatnosci()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Dostępność strony Poznaj Asknuts Polityka Prywatności", ((string[])(null)));
#line 23
this.ScenarioSetup(scenarioInfo);
#line 24
 testRunner.When("przejdę do /", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Jeśli ");
#line 25
 testRunner.And("kliknę przycisk Polityka prywatności", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Oraz ");
#line 26
 testRunner.Then("zobaczę tekst Poznaj AskNuts!", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Wtedy ");
#line 27
 testRunner.And("zobaczę tekst Gwarancja anonimowości!", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Oraz ");
#line 28
 testRunner.And("zobaczę tekst Przede wszystkim zaufani eksperci!", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Oraz ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
